keycloak:
  auth:
    existingSecret:
      name: keycloak
  proxyAddressForwarding: true
  image:
    repository: mylesagray/keycloak-arm
    tag: latest
  ingress:
    enabled: true
    hostname: keycloak.tanzu.blah.cloud
  extraEnvVars:
   - name: KEYCLOAK_FRONTEND_URL
     value: https://keycloak.tanzu.blah.cloud/auth
  postgresql:
    image:
      repository: postgres
      tag: 11.11
    postgresqlDataDir: /data/pgdata
    persistence:
      mountPath: /data/
    existingSecret: keycloak-postgresql