keycloak:
  auth:
    existingSecret:
      name: keycloak
  proxyAddressForwarding: true
  ingress:
    enabled: true
    hostname: sso.tanzu.blah.cloud
  extraEnvVars:
   - name: KEYCLOAK_FRONTEND_URL
     value: https://sso.tanzu.blah.cloud/auth
  postgresql:
    existingSecret: keycloak-postgresql
    volumePermissions:
      securityContext:
        runAsUser: 'auto'
    securityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    shmVolume:
      chmod:
        enabled: false
