keycloak:
#  auth:
#    existingSecret:
#      name: keycloak-secret
  image:
    repository: mylesagray/keycloak-arm
    tag: latest
  ingress:
    enabled: true
    hostname: keycloak.apps.blah.cloud
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  postgresql:
    image:
      repository: postgres
      tag: 11.11
    postgresqlDataDir: /data/pgdata
    persistence:
      mountPath: /data/