keycloak:
  auth:
    existingSecret:
      name: keycloak
      keyMapping:
        admin-password: admin-password
        management-password: management-password
        database-password: database-password
  image:
    repository: mylesagray/keycloak-arm
    tag: latest
  ingress:
    enabled: true
    hostname: keycloak.apps.blah.cloud
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  postgresql:
    image:
      repository: postgres
      tag: 11.11
    postgresqlDataDir: /data/pgdata
    persistence:
      mountPath: /data/
    existingSecret: keycloak-postgresql