keycloak:
  auth:
    existingSecret:
      name: keycloak
  image:
    repository: mylesagray/keycloak-arm
    tag: latest
  ingress:
    enabled: true
    hostname: keycloak.apps.blah.cloud
  extraStartupArgs: "-Dkeycloak.frontendUrl=https://keycloak.apps.blah.cloud/auth"
  postgresql:
    image:
      repository: postgres
      tag: 11.11
    postgresqlDataDir: /data/pgdata
    persistence:
      mountPath: /data/
    existingSecret: keycloak-postgresql