keycloak:
  auth:
    existingSecret:
      name: keycloak
  proxyAddressForwarding: true
  ingress:
    enabled: true
    hostname: sso.tanzu.blah.cloud
  extraEnvVars:
   - name: KEYCLOAK_FRONTEND_URL
     value: https://sso.tanzu.blah.cloud/auth
  postgresql:
    existingSecret: keycloak-postgresql
    securityContext:
      fsGroup: 1001
    containerSecurityContext:
      runAsUser: 1001
    volumePermissions:
      enabled: true
      securityContext:
        runAsUser: 1001
