metallb:
  rbac:
    create: true
  controller:
    image:
      repository: metallb/controller
  speaker:
    image:
      repository: metallb/speaker
  configInline:
    address-pools:
    - name: k8s-ip-space
      protocol: layer2
      addresses:
      - 192.168.1.51-192.168.1.99