apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAOw/Wp9Yc3DzXE6wILlYLbdZHD6c7PF2cg0C27G2nBlcoO6iC8z7k+uK8LThzWKvl9cFDgmOBHzZL1IU5D5rdNT0CI/UNsl6m8wAqZV1+r3M6q7v4+djL/Lg3WxVdzhoK4f2M3E2RHTU8+OqKBh0qC/nS15YfHFiy0vH17NYo/zTg4pB6z/Wx3WFSp9bxxwMQH1lPjcILP0g/w+HSMTaC+69izwcpEyx6iUYDVhZ7KLy3cXS68lMjRHdRLGJYthj5FLhjKIxxYnINe9dx0sPQe8WfpsQAGaD4DSE+JQRYaeSLyNB66rWxMi/2lGzTTYL44ULCscRXkShK99sXMs2RXIeoJf/XPrLLJMqTAY8/6sDu48rY1Xkh/uvY7iateCwftj+9dCO34f+OqnaWsZfnYQvaSoS6mG5coCqcR0bpdYa6NIeo2p/XdjfKopoUO5+jACOnmyEx1k8LJajGJ4cYT3ubzFxt492A7sOMgjbAXe5GHYmNGteUIivxe6j76UpQNBt9xG0KgxDVtsFXj2JjWDwSg05wvR3VIXvhdYjb7OeWqxT75Db39RWw0rsmY63FoKRe0khvW6tuRTZyTMj4w6deSj5O5Ixw2+REFDkZDR0Oyp//BapLAWVstoBwq0cN+ncHC5nJd8T5AGf2zb46qEs3Y2uHOOiT6NAGEpscNbjEeGEZcURYcINFPU+ebSWEV9f5CelVnknAD3PqKHqxCcqEROf3xvgRepx7DJOxZAyCJG8sGn4gz
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

