apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA1aMJ8uIL8jaZOmne+A9XyuWf6bhATd63w5g0GOfx9MNP607ZzGwZKdJ0y4BqB8Of5XDb3q4gn2wpys+RkHfksvcZ7VfP031JJsr8onBtWQCmJqCq2vvd/s3zqC1gd8QVhvoan6ILL8a61DmNL92dUcTaWw5ym5Zs6GJG8gTHrC9zuYw/cn6jUTwf5YKOPETbBvb9mFZ21wFmK/kJH3eChxLj0HSMhRLhR9JHXhWvSgY95niaHZItxQ1TkgNOCcXMvApR9X5ZCtv/BT9WH4VVYZUbTLYQGl1BuxfeC/bl5CQrglF6rwCfuv3qnAsWnVhSUFCf3X8slKgxruB1+UszMKGfUjCSRJ+aEK1pYxa6Yu/A6bgarr95j7hsKpRl8sWL5XECcrHt6X96mzY/SQTSm+uRevVFfDTEwWBbsf59M7si+bu38tpfm3LOB/6KjZJIyGKuCQCLeeNY4Z6u7AklyVWvmfLUaVCc0Y4Mgt1WgPoaUu/noR82YsDHZJxrKEq6A7we3R8wcEMT23k43Z8SKZ98H5BCYX6XPkzlCLL4YjVk36EpnRok5lxy3jfL2hfvOrdmg6522fx0UCw2MbotVuQ+wyg2Dtqm/L4l1bMtIDS7eskyayHjBHeeHT55CSUjxrFvX6CVmyfEa7aHUubsRKk1BKbVxt3LCSQEhl5HXf7mgGC5mAj+Ev46GvxX9LBtWh16RbmHXDn6dhSIB6sVtdojICXBwVisFgtmex8mDJ16c73Ks7L57
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

