apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAzHZR4zKUI2mdb8i5TeEpffIxhnghvuhqysxmNoWHyhxZ4+mBCBeJccCDFsN5r8vgswlcA6JcSFl6tPRu0kU10QfCtkczT29XIUMLn2DgR72YG7a/ZFdBF4ehvTsj8NQ4olpYE98JFEY2TieHiXrlW8b6VimN4EiiLJTa/25TPUOvS7E9zKVkIUr3X9np5ICaX/llRlfFLfao5tDp/6274CGA6E8Jjo7IwHQvKiIHghAr3cJqYp3Cj6svZK3nRPIWae/Ow7k7qcL1pwRECYhUbEoUdUl5emFuPD2/0nOF+jmpm4zC4uqhIL6YF1dM+MMN+E0omf9LEkK7yO1sdvNYurNx5hZ/mLVL0+vLI63+sqNUxNH/0ga85Ie2kTDrtafBStAA8wYc2Dkw8s/ZrcCYAfdowXD5kjVgqhjfvPNIlQiT4gzOBqB7mXUGiD4iqNZLEnOum1MPbTw2LoEW/bZSDq6ksxgfYdYXhxclhmCRiJiVfWNK09UvHzCpPT2hNVUHy++xUAS6i6zmGuQou+4/AKfR4UEiw62RlzyQE4Z5Sn3td44kGUU67eh4wGWvgBExPn32Q3Pc5x8tRpH0UJELVAS2XKcEQl/C1yYonQSDlZC7J/gmSo7QjSKiCObQ/fbBmGa+8aaGp5hBh9kRJSpHyl2oItdpvFFGE0VNvCv7QQEF6S2uOzTEALanQCDipr5VgucjYlfkRP5xtox7CNLMcuyatAdRJ92SOMZBXmsGrJLNcz9Jam0yi
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

