apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argocd
spec:
  encryptedData:
    client-id: AgAZSLCwXpNIdMVXvfQXmnM/DLeu9019jLwBlzF6nYjmClLF7q+KckuZpFU/9FhEUifnK160DQ3iCKCHzyZNvjHPktnv158lJsPDYemDbRTNUiO486THWj2blDy4+ducS0xUY+7dtPMwGMHxlnBpod2xMhgWeCgcFpXq9xqk4x7yeCL9E1sqeLs5LoqRbMOHhGTYsyx78tylrRhN0EWhBbrZgtgXElW6eNWpCZ7HohvXhmToykWcnsTsVDi3PVggJLnUuGJ3aeAQrAfEwh+KrS8Go/SLdyCLeHb93ketUzauB4PSCVHak8CJou0H1S+JZEPO/uudM5XheNbOgtavHfbUp49a5iHFQOr89GivNkEFGOVisentaQoHez7sCCF0gsFgLM5kTnAcxxeKRsR9dBVaguEek2ZVVsCsFwXrbIkWEqGy04NCdTDhG3YrzddDdPXydGime6k3Sn9AvnaY90TgBREV7lF5PbdU78hkRAAgM4ujxKdqfXgsNcREIJS34my5UVY+mObaTrH1ybZdFLr7cb7iGmdWxho8IM+I+rQ2KKJ8oAhWEqKpPfZpLnKlMnhNDmC1dWzUVxDEodB4IWWxn0WGFW8yFrnL9anm8as0e/M07Aai2D3FDCw5g/8it0Hts0zaxjh9Jyyk0EYv3Ay7ES/7S0uR6Ekq8/6vlpKsZ8pC6XYJHnun88t9cbvezZ4UkIyUObW/EPLOBgAv
    client-secret: AgCEWvTh3anqZlyC1ingaBAPa+uvz3oje52VX36w9kUMoQ27/6pu0M2oT1M6ZXLh8vXw5dgI3egaIgif0mLfrIJayc2UOuF4GOKYOLoxuPyWyen1PZF5o3AyaS08R98ZBm1TNQLPPpjGLkOfAfqrs0wh9PRZ0ZHoob3D7ec2w6TtPAayjQaUhjY9hLC1mp8cyThaJuntbQjuYxLQrqrlG+BRm/IKgcM7mF+XwNs/qkXemr8buAdOifc+JetRZCtgiBxLOkMtzTx3/shY3qN8oAsexW/si622tESQeRl2dg2lBg9damUhIp866DxRi4xKG8FIalS03nhM1/A04ou7NxAmyC1Qlk8HKIN7U0E0t/0SYY3lDCP+OZR6+mY+IvzCwcPuYTu+lU3DUqSgM6LD1+FPYMqrqOsQ3hHlQSTLcTjTenKH4t+EN6B3zq8iYGNjxRBoMrstkjValUQQDgW8y2mgNf3uwe6VS5rnjKi1+AQErxmp18l2K0fIcJwKb2Po4Fya+FDuWdRac43e6DSkhEltUF+lYFMRodTp+3N07JBwcM1dfDtbJCNk9eldHUehaQQL/0y/FbBTcKwN2/yxNbK7J84AgGyoWrIwsmWPCw6AQT46nw16Ft5xl4U+2JTaG9mY0tcgZ1v5AAPJliK8yupd/Uml//6l/XUxZ4ojRaWrCol4nJ3KPRkwijqybw50TkTvTLGHvv2gTdbRZ7w2s8BanCYh4c9uY/MdUN3wTIlXqw==
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argocd
    type: Opaque

