apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argocd
spec:
  encryptedData:
    client-id: AgBe3wyXrhs00xa+VAlVgr2FkPeRKB2uTTklqc75iqTIHwYxgRwz5ybCN8eI8Z1dXrLnysrN5O6pulKLtVlqb7gjQqZi3YdZKo9GG3GsaiNxY8pXoD+6+2o9oIdb2KSMh48xi3zLw592MPAGokgvTKUI90uF9Cdjdz0Lt6eJFu8LwHAmfC9f5sguwg0aruwRWXN7H96q1N899Q/N4xzdAm7M6aYRoj8U/btl51K+XlK2PSA+SD4dfXBo17YtZucK3zePx6MvcfAB538MSb+HsoSqxAYArw/9IG3AeTGKvinz7jOOfOG/xxYrAhr8Zntsl9OdcWMV2zSSb15Gz8QzSUHPVtYF5UFF93ADw6a2hr2j7MXsHtekVoH5AJnjbwT9Ll7F8i2CQcRUb/1FR7jMTR4xof4+nPhDRUmzW+i9vnrZNdC0pRH2oTpP/Vyswsp64D+QSRPDPUpbWLmZ8TNGWwJE2rMMUtrCflenFusGDhb58jetP9WYKPSqNxMBItFG707+6Yu/nsx4fEgRumSmIkymxEza+jk4iMEIDg+6APTnjtkGJD7vRq6qttgWOQUpoLp7XXJ8Bke0TUtDSEZ5ogh61/r192nGIYwYEm8rVX4hc0DU+cNlj3U6b8Y2mALBhCabHdX1BctcfnkuwPAprj+toCtl0eOWOtpj73sSyPxbHA2WErH0M7j0uxl4SQ+6QsVogKhIRrzxc+3KYulr
    client-secret: AgCeWaUmdD+1V1ih6ckmMn48/PyTLHwb37ocg/WhC21H/F7yBb5ly2Tg73IyOckEzEqOTSwAlmwSapmOKPzZ2/OP58x1iLDUFPRg2AXrmeC4TCgcVCTc3+AYF5cAnVnnRu64JklPPbg5EBMyrRvwzdRdwFsSGwvDHCYOYw+q9L1ZH0YrSn5wV8yPyz23uOc3nX+XatsJQQQKdJ0jHfTw+6iraVwlIqbBMpNHUW7GRclCuFioPPGR0PnfpzbGQKxwII31OPrpSXc7yAUrQaETrRfeBdzdPf3qq/rkt/VCdzZUhY7vf3e9keFcOgKFlqR+0eoxfJMXwcoMxmuitLtg/tSMnrN5tcu+AaGte4JT+evTuusy0p8NJRYGKp+dVLImGaftwZw3iE6K5vOrR24Z1m7pP+2fzTkpISfPZOgasgBkW8d1NmsIn4wolGeibiUiR7JyOfUSMTFHfIGpc9VskxjBNY3+cIN5uuxI4w/a4EE8LaCFfzEWva+/icVO+al8Wq43NpBGCeZZQDmLFclCeaLIPwyqqktJBw7UiOUKQf65ydi3Hs1n0IoevAyCJ+ellbLR3VoKzoLVxZLEh7+vOrfBYrJVzrKkgV6/af1paHjnvdbftXOOjq38ln2Bc/zw3qP0+rVLBBXBaho9F/cMToFiMfNdVR/HjKOgKGU8B9+WfkftP282P30HgvbPwSnmRUgLnPCjBa3cIqPEkVwTgva8vLlWEe1z6pkW5C6jzeExKg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argocd
    type: Opaque

