kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
      - grafana.tanzu.blah.cloud
    persistence:
      type: pvc
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 10Gi
    grafana.ini:
      server:
        root_url: https://grafana.tanzu.blah.cloud
  prometheus:
    thanosService:
      enabled: true
    ingress:
      enabled: true
      hosts:
      - prometheus.tanzu.blah.cloud
    thanosIngress:
      enabled: true
      hosts:
      - thanos.tanzu.blah.cloud
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 50Gi
  alertmanager:
    ingress:
      enabled: true
      hosts:
      - alertmanager.tanzu.blah.cloud