kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
      - grafana.tanzu.blah.cloud
    persistence:
      type: pvc
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 10Gi
    grafana.ini:
      server:
        root_url: https://grafana.tanzu.blah.cloud
      auth.generic_oauth:
        enabled: true
        name: "SSO"
        client_id: "grafana.tanzu.blah.cloud"
        client_secret: "e44e4dcc-06a2-4d67-9e28-1f17a39c91b2"
        auth_url: "https://sso.tanzu.blah.cloud/auth/realms/development/protocol/openid-connect/auth"
        token_url: "https://sso.tanzu.blah.cloud/auth/realms/development/protocol/openid-connect/token"
        api_url: "https://sso.tanzu.blah.cloud/auth/realms/development/protocol/openid-connect/userinfo"
        allow_sign_up: true
        email_attribute_name: email
        scopes: "openid profile email"
  prometheus:
    thanosService:
      enabled: true
    ingress:
      enabled: true
      hosts:
      - prometheus.tanzu.blah.cloud
    thanosIngress:
      enabled: true
      hosts:
      - thanos.tanzu.blah.cloud
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 50Gi
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
  alertmanager:
    ingress:
      enabled: true
      hosts:
      - alertmanager.tanzu.blah.cloud