apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-dnsprovider-config
  namespace: ingress
spec:
  encryptedData:
    CF_API_EMAIL: AgCA4P7PBlOWfFeH2zTemcAoEvtVxud7utY+uNCxO0gqUpc7DFxfflk8JdTVIJ9R2QECqpfzgPA7ZVcvjzHbfJm3ybou7drLSul0kK8e4BCHAr76t8mwtkbHx9gW5/4Bunt9fPQGeqeuQcF7OWjF/3QDPQMaR9T/DWyqAWdEmRMEgXQt7DqKGvqMvRlyjt0Wgw/A1cND5ZLoS1fe3H4QZDWjgg99++JMwJXHePms6fGkDTtQ/lYxLOarv7iVIMTgaKm04vn3SKaoK5gccZwzcPYK6WeF1mTo4omWK0B0jlmOvkg0GQjMmXhbJEsxvr4olxjpL8eSjvULytXNJzkliJm+MREK3+OCcPu60nW0p+RcnBYtxtquXb70l9v3zTFDIcQBBkZUgfaralyjCOtgkYOag5HICI2pkWedCkydRavi6pwN2yFjlVXl7eOM31mWEieBGvhVqg0N51u3nob8TznnToFT3lejpy2v9wS5a7oTnzl2ZHBBrv/cP2MVX7yXjf9+HpzK7UOx0FtyRiY4qk2/sQ/YDcUFZgPzrDj16WGs9qOVw+13PnzgXKQ2J2zsVFqF6s6AoXgSb8Yjo+is8ZGh/3eQlYufD7bAe3DFOgKN+osQ0hC/zWjbw2Xkf/8uAmUXBsxLb7Js0JKBynM8j1MVS2zxGJzbENMXMJL7gU0iQhCfLjpSnx4m0CkZJlwx5U0kCw+mu/v0thIrECGH+ggb
    CF_API_KEY: AgCD/jIU46lcMu0m50ebZiiDNBlDHGcLVliLBmvO+ateVWmQerHzP1W/mJJoGqeQBNqOXvSLT9/EmKnV7uu+gkwGKuNBbwoeMU+C15Tmz1Cg0uHWVfKctRS6uSsX3i5CE1TmO6z6eyLlPQbk2jXzwclovWblFFG7S0nf0uKw12bRWhCFFGFbTGT9/rxzwRlqHcW3QLD1+E6b7pXhGIw8LK04IqIrwXkP8gjG/h7stLdu4FRETXcjLDORrrFLX0qWtZZHv7yn3PrsedGSaYPYfLX2adRWkNQEtyZNQUY+Xk42XjIZFyp7WnViurs8TWzULfcJMXffBlTAMamsJxi6amEC5gEzOy1PwgQVbMpeFc1I+h4GTltjxrFQR3lwaQSuUvqcyCCkXNcs5HpaHVwV3HaWS5NRnzQcw22Tl7fFEnMloNX6TTGqriyEp7+HEByu1izBjfFHogEG5L4+QCpBmg4pHJf2Cosm68hTUr99V4AsOJy+PmBwQoeW6CYUScLGRwvERjQdOazc2ywPQHP72Rm7Njow1vhg/EMef60F0eTG9WJR2t6svMaytriSxwwczq1DX+UOYk27t8DYj9vo1n0oEQklz7lddtxrqYXF/fT6tuHuftuQThKouTMYRoCbSznkc+FyqsMTrRoooJvnZOkwwCNvr/IwLMKh8ef1IzbwMlfa9K5dZaKTXr6G0++G5MtIzaZe6Z0el87IgQiaYCR4gc3qG3FaQnTRUsSTKHTcY8Fy1s/P
  template:
    metadata:
      creationTimestamp: null
      name: traefik-dnsprovider-config
      namespace: ingress
    type: Opaque

