argo:
  workflow:
    serviceAccount:
      create: true
    rbac:
      create: true
  controller:
    metricsConfig:
      enabled: true
    telemetryConfig:
      enabled: true
    serviceMonitor:
      enabled: true
  server:
    ingress:
      enabled: true
      hosts:
        - argo-workflows.apps.blah.cloud
    extraArgs:
         - --auth-mode=sso
       sso:
         issuer: https://argocd.apps.blah.cloud/api/dex
         clientId:
           name: argo-workflows-sso
           key: client-id
         clientSecret:
           name: argo-workflows-sso
           key: client-secret
         redirectUrl: https://argo-workflows.apps.blah.cloud/oauth2/callback
  useDefaultArtifactRepo: true
  artifactRepository:
    archiveLogs: true
  minio:
    install: true
    defaultBucket:
      enabled: true
      name: argo-artifacts
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master