apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-creds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgB7GxR8nMBbNkyMRCWMnBCQOoHae9rj/xXu/x+H450WaAmv6/dCf6fJR8Gm32Q79KYAVPaqgF89zMXUh7+JK3rHViOcKQOigPPj/gb/nysNPpzR8MtPVrX9TR+XXBnQ3WOwSCtr6vtM9Ayv15Cc6H09L3V/P1L7LTvVM3Tzu3LC6qleyPsGikdE/HehlC9LBaGMMiAe2zeTb71NzBmoaDqo2FAbmmEdshuHq4seMA3M4gmoMh0feTW7oGPR8aSaLWWF9Ncl4KiI46be+yeIaF/0XGRwYRPfvNuCCTjnCFc4ZXcAS1MyzwWOcf/u8A1mX/eBmIAtHF85w4cix0eeAhqNZ408EFFf3q/v5pLSfT22DEwENZnHFAyd/Eknz61XZnivDGFSltl+gqlcjcGOmJZ/F4oaLZwI02M1qifoOhCHSaS5xTvbWsvQvwqQNtqIcJgCyVH53N/HNwEvIE0IcKumyl8EtWdDMpyAnqnD3PZEIv7258HbEuXLuB4vp0pptOMOUMIslFLCW0ZeTbV77iWXMzkbWp5kXUO4QkK3JxOBaAUw0XukqU0aMg3iBD3LKL8LquEy+mwat+zM7wGW9in+78CvX+KdrSGpQakHI+gWZJScd33BGXdpaRcu01cKUsRlG2yRPAZYFWDvankcKP6Jk1QkNQ+tfL6xGJ5haj1PUW6P8Z62/tGAg9JmoO3Vx8Ww5/kxJLsW39XzVL1glvnzhVlO2hFdVb5CcctgCWFY0td9C+RMCpryKeGr4exfvTsxaJ96Uf6QBJ1FOOz3fCKfJ706+ruTawased5o/RePDvquUccNAALtgWi05RKEG+ycJlrx6RravJNu37FYnzwer1nal97L1yeaU49Ro7bDT2j5GyY6QavHVKxhrL0lpl/z0ADokeVk4gsPCUhgD+xvbScoJBc48Id24HPUkk+lVxDPXXGdTzhUADvhVHfE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: docker-creds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

