apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-creds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBOeVsjpCTSGzRyLKGjVmA+rmKndcvND9VQkJDs33zEJRTa/ebifaiZUdQ4MEinJipizSwFwdkfhYI5FCcCr7fiGkvw0tKixi0jAAWRZcUsqp2JS8qpIkPEuo+KWHMAuqypTB+0OUwn1AamAyoh3puPnWVpdT+G67+hOztrkQlgH0emzVwFymdh3KBzOt84kHj1jtdD/q6yqg2CQmnHVV+ktzEoJrwtc0hFkQArrXul+GviaTeInmjH5PJBxy1b0gYjYoNt/mNwpgQFSA1h0I9wV4Rbbpm74hbFDEYw/3KDWzGaPvXiwv0entoN6HDH/BReKeUAwqIMYj+yV0HzmzP1Epq4An257OkyAhHv8eoncCd32txgzy4+B6rJHStIy+fHuG7zkvM+g/3Yjw249AeBatxFphzxT3lYzMGS0TRYuPIifdUBYZE1NXAmGMxY3DXUWDWjn+0xeQgKXKmBZ8yOkZ3AlDpRzNkKwpbR1MmpbELCb9dtu+du3/BPhcjTCGLUnQH14RF+615NNiP3N2EiXcGUILt8H8snftgwne2WV88rHqBLHn2cTB+MCu1Wj6+oXvFkg6klf97FOYIEDKkp1J8Zo4cEip2xdah5d3rX4CUmIiYIBfqIGkC5E5p/QXrqJr981/a5SkQihtu8FA7s+7QplVg4GPEGoahp1Ad+L4F1snFnraDdeSzr/MUCQPtK75OcFXyc8gNVP5dhdufclNsiBO5MRW0YamQ/6/bLQL+NasPtqSrmoekMgQR6wU/bKn7xeLvMcyVndBrTiMvtGnOBFBj5jukViWHBKO3PxK68YOz5eL56apN5eJH0bgYFLuHacq0yfl7bR2ImQFiyI08NKvHyIF4RRgul8ujx2O+ASeB/9+UNknbIDXCK01SNkZogENIcajGD3WgFgjXHSXb23o9H5c+HLn+DuifD6Sj8ihg0k6m3GyugDKWX
  template:
    metadata:
      creationTimestamp: null
      name: docker-creds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

