apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-creds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBJIXujQmmIVlcyC4cDU6y1UXtktO3Iks9n9UVuyTlZ8cl6GiKJckuE5D07qKM5ZND7QM+LmVF7PMOwJ9wGOkMbakanfvEtCBwPXRQSE1w4cw00e8AG0XHU2Z69SY3g9iphlyxgaWXlfCUBt/r+6WuIRLnYXogQQZV4+hOCgSez8H1s3PvuiBvbR3J/c7JAXHzRRhAPovlVcm5q0qD7XfKX7UBRCKD7RfkEMOE/nDAabVFWtKaB7/+rpGdL3hV5LLTnL329gWvu305GFo2Cq3orJ39Votz+5GNTrJrz7gdyVVXkLAy/7HzoSkKBhEIMckacz68ENFqoWU5Ic8fLqu0/NOXI53XZilJltPrUtHsY/mDvR9BvFzE5Ey4S0HQCA9tWSKASJA6wFlcgYLg23J154/gibzNovM8cKJI+p6WIeps0OopPRwJZh21CEMHVmOilMbdtYZ+caI+PkxK4gsLweHrqzf+VxLTxTcbepIvktTiElrF0rJ54fdnaDpNaLplRvXBApgTGdRDwl9TN1SkfA7sn4FgF3UARgg4Jcgt8Q4XliKpEo1/trgIwFm4KiTKHC8kBlDcP8B8aqOhp0lwOZwH2i/q+o3QaGQtF37nULnRxWCq/56zPGQaih2DRyaepfUOlzUwnYDZMiwL8k0e7LIVkLKl3xdbdRp8HvZ3dwALkcWb2KPSXcck0AFmkmcyLfJTeHgfR1nH1J7HwGCmCS4BDaoWy9uPtgSJzKQJA4u3LD+d2N4pS+8R3R1Dq1TBidOVNMJttPMQGpHbSARhRC9NnMipJnBWf+kbBxNfPvG4S8B4vIH7OiA76lZq7a6k6eBoPidux4v6undsAs4CCxnlWjvwOcIXQ/W8lpi/BW1oeLiuHDw8ls43l5kxTq1jJ91VFdGk/28Yx1IJRTo2hc0vpgIa1HPIlg/Lp5rJqk5T+7fyWTzzMGK/MdtaC
  template:
    metadata:
      creationTimestamp: null
      name: docker-creds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

