apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-creds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgCuk0YSiuc65UqOTwUY94pKVt2Ymk54S/jHxhAWzu4pIlnPTEEi24TvDHmDZQs7O+nzLQGj9a8zPSW+eCGZ6TGdiECwD34rOihOuz2GMlMdEC1wOhS8L7DBz/IWrBKo79LEbHeY4qVKPWB+m/uwoxeXblBrddXYOHz7OJpGLlirDuv4ZOOTekzDVwiM/unVawdYDbeBYmXWGvh6rv85ZEZj4ZY+WpwIMXafRL65nMSfNhRi2wpEqno+BqD9RGBtzGJu7nhFczt/BDOUv7GTtEz5031LYrZQPSSqO+iyXMHbv3Q6nBkIHUropDFCRQQ4hflq+WGI/V1mIl68Y/TnjBCpuxKgDFWNCbOvyy51L+v7SMhSRK5gwKch+nM1erxEpaiugVd9op6ORps4GrS0pyRpnUtxBSyEGeEh4I7nGP+1rHuomREH/AZvtnZuJPkCN5RH5yMUMPWUndxNzFHJnoCaCdkz5T1OTjZ9QhVJCrj6j7SXU5HPljutAuRaPwTKsOOtUHNqkTKWXn7HUVjemm8Z2/+zDNXvd2St1CzJTuiVzHQcsZBXEOl1fKMYCPYrUx3Xlay7k5vyc0WigEQ2EhjN5ugItZEGxA8AeVusgEZXn+qmWiCVs0dj9sXYI73Z3n8T1ZCROGCR2VT5ruSWQsf0qpt50gfcXwdYb91H18V8GI2J0yMTybiL9Z8BKD2C4UO/sCFu9ZQ8NHBa1uq1vFN5SsCm/C8bpGBqAV/rxk7numAzpZI+Q5OAmqIAGb2j9HO7Zn8DPCpYRqT3PCIwjnGhWtYBEmf/vQXZ+G8GQctem7xAdQWJGx8t+oag8Mz8bbJun/Ysbiyg1Gu9NDoxQX4oOnkSM4R3po0IeAc2xDmpO1Zf49MtRwpoSB3vDkDICo2WyO0l0z9ggfOSijch7qVWEA/r1BDTgHn5b4fraae1OSfYXB9hRWWKn52xPCMO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: docker-creds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

