spec:
  project: infra
  source:
    repoURL: 'https://github.com/mylesagray/tanzu-cluster-gitops.git'
    targetRevision: HEAD
  destination:
    server: 'sv-clu01-argocd-ns'
    namespace: myles-ns-01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true