apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: quake
  name: quake
  namespace: monitoring
spec:
  endpoints:
    - targetPort: 8080
      interval: 5s
  namespaceSelector:
    matchNames:
      - quake
  selector:
    matchLabels:
      run: quake