apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ci
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: kubernetes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: CI/CD Components
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'