apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgAAP3X5f4P22M71EdDp0fUNFB2MEQ/0mGAmrxhjMr6TyqJtNf7aDXYsGE7cv1R4dE+kX9ANXNAL/vdFQYrwPtnkK2T8gbZCw3JcS2MwOZX1Gw4Hg2SeH0YsIGgUgkA5tXREYYLN/dzH6rPE4y561rC3tuYPXp734LIsraDkgcE9m9W+AJxLnOuO6KsW32xZR4/Kv9s9nRBi5l1gWhB0GRJmIhKNtZ4zZP9x9hcezm2dSXDOCgwcGOi9g3Bl+21ddpy0+SCkonVSjegruUOuX63Uo5yHvxyiL/0ZUrO77ecXm2gsGorKQTo5+Y6UCbp0E1MnHJPqLOjiQbslkBjNGxga512FSukA1g2PiyLnTi3yWYniOu9fVXEWeB5AgHHvghdfnOtC6Fxh8euDAx82FtnU75fWrdbwMYlLaYbNxUbBrn+DFd0b9WEpyeOCEKT4YyWKHgj+5+IsME5uI+d49+D3k2sNmKC+0hmQyN8se5l2Gz+CVmlYhDsuYlKBHCSq3G2Mqd1tKp4PFBiSwnecov32QE3kIhtPm8PZplGgFZWjutLkuuEM32lvqjXnANW9jtMUaipaikrCzKCt4aZEHEXr+4aziXqcsOifkZQgyPXEJpFEZjXbWXjh1p6i9I1u3OADwrCXA2Kq6zAR0pPzXmNY46l1AIutAodBCJbQXbSAnbFGmMN92m9TYmgy/TnUblCfs8ngUgiLWhZGMBNw
    postgresql-postgres-password: AgBQBAKI0SJL8gStEECO9rQmLzDQqyZCjQyn6duoFw+smuhB1sXAbzD4M9E7Yu4Yxh3TTgtVSewd4Ww9SHfwkc76oAovyrLPlhxLbaMvl/l8Y5sngIzpVdz2ByJpiOSCU1nkRPFLD7aqhsFwlEwIPwe/Ekc+hDEAsMcsBxSDkvL1CL9JjpyVl35QylhfCX1RmtmaXdPhzzlTOf3doG8CpYlwQ8WDXuJE7Gy9EpjLtBeAJwpEGs6hYVBO8uzfwJ9xvZ9HcR6kU5rWqgQAcHFItH56R3S37MujsTrmG4Qh2G1ApQrQdTtjakICUd/2oOShn47f7luXuSc6oG/E7ynVkN40abBM5J+9Bjp6wgF/wlHW7JculGDWoZnCUJjiYG7Hjo49gJFdwqEddecW7F+UGSd80TsfJ+BIaMjFBk9sB3MmHtiCfrPr4fSiY/9ktmWxCCzZ3Catff8s4T34rY18EdFeEzDCvOMYdnnTZnkcrhW98Lj6+2nD342Gna65ti8jkui1WxRtX1XfMeHjHf5KASUZZrXsqP4p8VivtgiafDOAinbGm1k892oakeHwcCB6YijMdLK/VEf15UiNrOqv5W/etBL3ZcM3KkxvOBfqIklqr/Zvx+BSf4qcEntP3GOp6+rw4vd6tawvdwLuwVmreepvYYdwITu6/7RazUrEHYGafWgGxg/F4f/BIfCQCu/O/wDM7SSWosFe/myi
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

