apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgAJVRfDuYqKsmV4X7oePAju/10M9qJMlQMCxS/lIYb/YY0NYOjTf2SWr5pzNCrOQZeJfrY4bggldkfDfq46WdXY9NuDpdvbB5Phwi9YOVLvV9wor1ulxg7mMLzZmCVLFJbrAxgHs5fiYNregLvsecmzz44Mn25iLO9T0Qxk8FNK3wFWcwTlhZ9ZRmQimg/qB0oPQqYqdKcTN+eGg/obkFAj91P52OrkQcJEhh0TMwKLMNHHj7MCKXEX+Wt7MWNTvlPr6IwRTm1vB3SxI3K/PxbgQgivu3iGj5qWoInnexj/wMjnl7xK/ElXDoNqiXD6GVi92w6uFluOgKPKKBdAqNDBALqjUalr28598zBrUXf8pn6MiBCqUZBty7VHCadEofagvXy4fBZlIXfnL1onLe3gypOTWQTXXqiMxwHQclrwy53m49yzR8NZvV6t+vxbvnuuoxbJcGSXUe2uEnff3AGRm4sA9126CS7MzA3G5ecNRxpQfZNAC/abBCq1YNXFhkpKTi9a59hBiyYGqCgUobFYKl+YwlcHANFnaUPhjc1Z9G2EH9wRLHvPp/X5w6pqWrzTd6I5fN3a79N+1hGYcMuJZjbuh3JKB8y9R5fcH0KboZou7jPHcg2+aYOlbERQE2DzmAvZBXz2PkY2y3dnTp3qt8uzkaCk11zVi6BjbZahe5sguci4LR3ztYOacZ93ypX78ra620xQ
    postgresql-postgres-password: AgAWET9bKTi7m6fakqHXnfSLobvzPXDjoKTW1nbzRhuJ43fJl3S8eGz57fVsB7sATcBzmLGdJq1dRm9wYQ5/VThypIJnzwuLLAGuj5xDrw5oX6bDvvZ4yALt9PUFjQCYkm0feV20HvHMvMtS9wP+9+U85R//Ljkzi/4V+MqLeQAnsOzfQfDJ7MX8HChoVXO4oLRPG1O9YKLmHKiWsxOtQs6ldCAH9MVjIRKjceSe5RjkEnEDDAA0Pb2zqgmM2tW9WNoiSDC+CKafnqhqmroQdZ9Rzahj7jaEXFGJgxFwqlns9x0wcHj5ALTMHbRxV+GOEq6C97oGXnlSaWBss0Rw6z3U9oAwG+WsYJumVmD+1FhWtNFefit1qS4pbfCdA4GqQdUWcZvgKRGlI0mb/FCKtW9AKkfEKXCLE5bejP/vRjyw7ZQgCVzz5lnswkCfL4PLkSMEt+dA0ZJF++WQylgMST+glQ9iGHcTyqgiONQGfYpVchRhRbuUx1GFCCknvxLR5a7LB+TfB/LxeB9dLgcWgnJYAhXfVreL0+b0fWcvI75/X/qS3ZW4YzHIOiV394ZnA0penpNuz5JinzCFt3nAqy3yM+dXA39EDTSD3q/3jJqrKQvviDXQ5ZXihHlrnV27JLRTW6Tfd5MQGuo6641mJp7Jp4tKBZsM90T2dFK7hdr175RYFuivOxsoYgaryqUOzvFuaLIukWMm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

