apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgCd7KoQ+gdhxySu4bZ/56BBnmJIPkdVNtrR5lYJyR6JM0k3bw53TXmrbc4YiJFJZVhNLzoThtIkxsjLb+wQ76zl4USHOzs/6iQ8IbWRnHNJUKglhOHXCGC+m5YfwIzSpjKrptnL/K8zkHDreoYMv3hjiMzl+syNBV+vVlWB9KWhXDHOTRn7Kbtjg2qOVuto/na+bsG3KXKqzGAsXHVB2PRM/wcy8YZhSXbCmmfC/jhQm3Ff4rMusAAYTk90N+cjAyHU97hAlRJKKHvuLQmWOA3B2lwPK6u8rfQuWhE2CaIzOkFz6/f+2edQiOqEtQ9qAjQ+Vp/u24bPB1NPIr+GizD75sT68NGmBmM0GN0y4JCxtrc0KyK5rg6d+A0DELLmXayj5mbMe3RrUDngRxQFm/4lQALyijCqXU8CoFUUWyce/gRY27T3z+1sEosyPx911mHY3M7jSq4KmWxZ5sDGDfN+IZMLGLEYDU03D3pIPbUmeZ7JjFUTq+JWpeo/O5c26FUrlKiQ7c1YFlzbV5BNkisSCREy2o6R8aamDouBH8Rtz9E6hu8rDdJ5rmAfdsUEAf9m3F7OdDHM8jW5TqyYMOpzAvL6EWGy4sb3IayOJKhXSFeG6zSBOeqoUm5AqaaZheukzQsK8ob9qD4PyuEfP9mm3tdZcvgS5b0rwdI/QLEatP6UlP9M2caFn18F/Heq/yHj1PNk7i73
    postgresql-postgres-password: AgC6gp1ZYcWkqZ+bAFt1cGcBWNECW71/Z7LZ3uLJlM6eWteHhxpWc0Hz8HoAT3ToeKo6WTShwCfLiZwf1/q7ZOPsRHycHjSlvFGGJuKJjKNO0V64MdoqdlcJxiVXBc+NW62JsrVfmSMQ+I+InbsHMFJIed2Nlvm5KO0cEBSVC2jnm7AIPETQb1VE+ptsibP7VZ8ARg0WDYBzdAUFH5x/8whZ5UiX7Jwnz4qZ1fozdJMtxkmXBU3H322TPIQ+7hYwi4+bBWQ4bKDOhOCvGlCl+GasX4NYBHKHyAN4ebfWWtMqmRbFUTMg7aaVPrTEDlxViHothXpgSgDsGUBv2oFPpzcd/KtbtTHw1aDyrNPV/urF7RYqjSz+VbbGnpaRJG9FL/xD4qk18pZRMXiFO1WJCensBsl2c2ec0Pe0whcpXZzkyditS1dgFwdSRLwlsXlofBLa0M9VBqPJpREfKxh+p/bFV21OJxP2OsaV0JvT5oRxMDEcpUHN1gCWLaoBiQL49gnlRQFiHDIpHwFIxiAd3iJ4KSvUb4VGvm0i2afD0VNVweE2mDqFD4Xhx7J7f0j/o7e0ySJpCFkvhU37U3cE4B/HOxubK45aNSjXMNZQJG46cgTph2bMqoxdezu/R+D2WYbJYNg4LEeCt8YlaSgG7z/+QDgQU2ZkBjJ7lLNp8vJAVdHEbtvA4sh7T309/N0EmcXEPDdExPyl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

