apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgAj5nLmcAmEm3kZe8mE6ojb0ow8B8aDpN9vDDw5uXkFe3TBKtslU+WL7Jj63mdCogfkJOpE5vsZFAqE59/WvPL3Kxo29Dss8giVSGXS5QnTGgEzzd/CZPHB+4wttz0d4E66d+10dYMuJ+N33BF2SmJzTnAS5ug9hBbzhpcpkEiqgI/Acx7Ga3bj0XpE009RcAfvRrTQS6ODNrwbatIcrj/RJ7g+U3lssO4qouKNY58AorRuMsh0XNnYHhFR8mTz+9FNzJWBtOsicGwlr4gbdg3rzvIoAzTbD7PY1Y0jAWkewU1nIdax1e/7/V1ufvzApzQis0/tWdaLolhnppifn5G6KleBqa2Q9nVF9xqkMwfEC3udeFT19QUWL2JJBa9slrDfeuLKG/p1boGwslUDeicauq1imudu/Ws9mOBGW79wVmY+8rNOhaPdQiHZMBM7ixRVUpLW7Vtc/7nPLvjx8bNFjpCWj5Ri2NSqWV49THGoJCYtWmtfTOPj8DFVi9xkrstYJRQpTyhEjY8hQue7ups8pH4qkpQGji5RH39+FG/UGLht/gnpZz/IUGVEsZvPrZa6vJxiqWcDiiBH1OFltCSj0I5ha0Soq4r6uETNxSQxTJgnMBsQ4F8EN68ADAeEmr2HklSmz6qPBFetthz5JqoKS7NhnsuUJDKuUI3hpOO6jgBiv5MPERgGATsPbpu4aMHE5Q1XJCqu
    postgresql-postgres-password: AgALCPcJ+kvBsD/Wl4eYZGp6rfSO7Oi77jflDWRm7MrkBF7dhxBLJvhzlKpKEoDXgnmGbCNziJS0SB4UTL6XiFQmXbSLMkXFjFq3rFRA/FKfRmkWhQamv69uiBhGXivq7LJxCZZjRr6qFouUwiouzSZPhiMWy2Fx7bA0qE0Y9BiNr5+7ChN57YKVHHxZ1sW/sGvg8JZV/BdleYiWooEqCEEiqToe8d+RU0SC6YxE744op/2jDsrRk0u0lhqWJmqDFfMFg6q7N+X5XfKSz+a9E6IjwLOFhfuI0jqnfuLqRhYU37yWNUz8V4nv+H9kFQzDZ4Ts3f9kuZMDif1cUasr3LaxjI2qhZwpzfRwe5XYYFNqa/9RAVF30UIJCxamCpJ3/byjqnrsSkNuhCATOsT689Y76KvUkEcJWquIofylRckJdkmidC4Y0mefMgd1qtzSYUvPUU3E6jhmQL55dp/+10G5oYUYq8AmLs2z03VFCRLUvGAd8GpXAhAKeV4ZJv3SUzKbtOep3GPT79yyxTt84kAcqF9ONWIR68vnUPhQNe2AuR57FlzzGaFmhGki9mfhRW2wTPj5DP56KKjSQHzvL8x7SjuCXPfIxumW6SumIRVTZBpJFaG4/ssPjEIOB1EKhm6tIQnPGlOlqZCh7bpxLxLynpfyUzc1gsv5wsqyDl6nXNQaFd4BGj+qfGF7H9TATgtcfg2w4ASH
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

