apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgC5rAfZV62GtjIyK15r/D2nDSVkmxNTc4SMYLsALjFpv0lwjvr2VKN5Xd+iibSRaqazK28Ez5sdu6CR83VcnSISenmRlw0OtzqmpbkzrJxZyX/oGiPtK3Tkv5sW507d3Hx/3hFtMzxCRoLO8bh5p93SMnuxODCwkeIvicJ4LE38PUSeYuRPtVKjqqFFmPEqQuUKmY2MeKciHsWzBZAR0gNTjyceRz3aB4PjhvSelPCttD6+w0fbh/Gs+pvVQ1+vxljA+nP3t3ZMkx4TLGKGdT90nNIjqe8oU4uk4/ZO9qXRimSeep0oBNkfqgN4IYzTWn6RwC5EVH0UfAmhTvw8Yq/+tu8vC1otRD7z5M4408HEmailqmbfitcFe4Nz4Q04SQHqdA/sHZnnzDIH4HmFal6gtHnGxNx4V4VLQtyvxrdll4QCwPrvvNRamrKHQQOjoys6I7wcIt42LCas4Hh03RQMcJjGx/DpZOTPt2a4ChOAoHKkFtmIp+b9tCB49Zpcn0oo5dJLOntL8k0+jwR2uQwMQVSaSrFEdDv7cBta11Z+3/UWnF/d9QnveQ/iq+u77aIcjc1ij6rBSKWCgh5t6VHFYz9pf53CTFBoeKoFsnjwrLnmfKhU2Ug/YzDv1fjQ9CvPaqupczCLEm6VTtUB9ZYl96qoMaeH2cEZezvtRw4Zz6ANV+sX7XnvGgbrBC1kdzEzTIRTdQsit/YOaDTb
    postgresql-postgres-password: AgB7AySQ0C8u52OyQretmmq1DIvPalS0pgbQEekhw810Lc3WOHlZZBN2tL0PzNfHnO1M7SHa4ZuXxCdr2/ok1pHEkuxC5LIJ+5jzxFyoNx7tIOGJLkwuKPVcLY6rhbgjxJuCvKuCRF4RoJsnfwbe6AsdVpIVMTCvGcHcNRgc0qsu7sdDoYfTT2J4UOrCg97O+ut9t3LhigVfR1nU+DdfpdvYJU8Vd+gIjz/utsoG13vpEVlYPnx/xTUI0cyk7V1QRmbfaSbLZ1jbCH0KHvKbbtjayFS6Wj7zqCtugqD2X5xX5c61rnjTWjoGEMdRRg44wg3/tn6QAdMRIQfOHHPNXfbUWhsjv/6swWrCU06RGKQVw+VmAJMdhZeav5hpGc3IRyQjb2LBgCNBlmaRFlYmmXpsMqNitabC84RaRJqIUlg2/2X6lCgJ9AgGLHSKfsGt943tDic9FTXh9esZ151CvpHMA1qMiLaGrTdfv0L5R9bn+FVjIhdgvkAJ6v4w0+9Xf5GAZMiK5MZkPd2fPV+wtxrH5V1v2lNu/5ZMEoomXPcB/oy/DkhiGL0HqFAnJhcs+ChQWZJkZFGitkcarzbYSFMv8GHN2j7c+cmrLo5uEvq2ObKdxDKIqQFrzPFDuLuM5jYs9BZPoBpfRcp8h7Dv7YGW/nz4xTxf2TfeQfJHLbMOjcx4RIib+on8LGkuSqIHUXMzmAnxcZ5Zcj3e
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

