apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgC0O9TB+5aKR2o/LRm+xnxXruGMCzcx1JSw63xGIUHz0rBeCnMsnO2p4pSDjS0/wPiaXx5dAT3EnVoukvwydy84GqKeasyPz2RN+XeuOzt3Ef4nM4byEbIDjBoroPg/VuL1aFh6SaNjahVtxKJmjEzVaq5DMFb03jeCTq0R93E06zMh3e7YSpPWTh9v1tX9x7ePhZ/cDm6zKMpDqKLGuJdKKZ1IgiL8TkDlvNr0NhMMwGQGCRKs5l3RchU9wKUYruvu2psuxvgdy5zAfulcC9YUPZE8gnh3UXiZYXVJs0BE1S9y8lIqgch5vGweBDZ8KPc0Qz3oAI+JaGrnAJ9lbq6MJTMOXk3KXzX818RXJJfWtcmQfw/9XNMnniz0qrpEykhYnm00K7BULMBVMKjHxH3pC5qgvmnUzw37edjkp8ucRgTTVDwS71r5jAMetZQekJM90vkGUqSZ9ni4Vgjw1lPU0oMCQuhRHvE0m4moFYJJY28l5QsekaU5YWeBT7Pw59nQaZuLtBA7OvaAJvtkW8oGAIvLGQRGEg0I/4N4C1c0VAR0ra7HAG5yhqs/FotZKmj5h4KA1XhYBU/cK1PFRdKzlj5v+71Qrp9QzxsX/Or1nKVOIVDh6KcTesqVDKrijTLV1Cv/KYV/1NyZ5te6gngmz5KDCIHjJ2vPNfl1xPUFRjumaL/5foM27yZIvZ6j+EE5LaPFBMan
    postgresql-postgres-password: AgA130tsBfxKCmChVkkmffSZgaw5ZOqWwNWhOiH7Tyz+YHdlwWg/XNUALua+GsPx8bVa7hnL6drPPpYOiVmMWmT6pZRmU7npH2Wyg8CkWIZ2Kg1IeTnABvI8a4dHuP4ynYsanGGdrDYWU8ZjmJ1OIuuO/RLRH784+2ELiTKe/Z8FQjiC+pCnOUYq1IpjJVSZas0La6D2TwfqS7mHMhd+BWJy9sySHoaakVn295R8gAW9U4dtarxHPphlssfd/9EUnDN94C/VTlFpLfh+n4rmu5vZatqonXn9erKNYBey8nhrB1q0/Wq3leGJfvB/9ClOoVB+txIDm/D9fkpdMxZc5p604DOARhhrVWQRysa4GNFOI4qPeGyjIoP1jc3pFEzypbb6gzGlEmH4DqCR4XW+pvjm6aHY0FTaGo52tJ6W3XDaJ7qDwEwQi0pf6WZCBUC/twNyJaWr36Zt/kDH1x8IDcHv30VLK5o2BHxC7X8wrUI2RQkszxx1gBfAJAMMX+fyGRvohhiTFXiwNNuv9t0Yg8WxnRrq6gBQEvJBhvpccw+Px1ey/6Y2t3wnqPITgzfnfPGNY1Vaxj43EiIZ3aL25/ruxJk+8i6aNt2Bdw13AvGf2P43RdrPtseLOY8QqL5vQlcNVVvRIfQmjUmMYOJgHu9hyTzuGDB0QDUUmUb7LJJmKiiFBeQPKkBxxUS4zeYedns19y1JKmRQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

