apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgAkY9PUvVMewOXYyxszaRy4YKxVGeaiOhFCkqDEdyCe45DGPy1rwEiam33pH72TccxxXIN5ylkthl6Mj/L6v6myoAMn+gAfwUDWrQM9zT2HkF5UQ5Bityc8rmFLv5Wgozwc1OZ2p5EObbD8mpdlRyMLI0jHDa5nh8td+5SLce3D4x2e9i+xADoMbka0rWf8n7hRKAEibdvvcCdOat9eNCmr/cdZZcAMEuh72IZGxRIlRqY4JxOg/bzYPXtl0QYdr7ejR08euIMQZMkb9IqiWL3mhy7VLEwqpgT+t5b2cphJS77D0BdY2L4dp54KAVqLoNQ6WK/NreMc/XuMj8lWXBc3hQRKhzBMtmqkH6ci5h9LrYM8ZzaIu9QUytdOyEoNgOsxtDxhokyNc/DcZiUJEodcK76A/2PBVXxiW4f2+5CO0rQUnJ9rnUKYhlljAdTSjj2H4fbhsC94mkFKZ4aoB7lYtSC4D6BETl8aNs7fWhEq0c089r7z1n7L2tjRnl7yHWcoFLLXHnONHQYXa9a6eZmCrxDB01LGViIUTjNcLzolgyX14+Ub+mBgG+uFByz2rp9q2rpnftmva/beVu7HbiN3lDfjCa8lDWqCI3GqUm2+4hWxVe+yA8xuBcDD6Q5ado6hV4o/OP4CZmv0OqTaJQ6i3egz6V5KMRr5nTZcMwbwoVU7FJCYcagmrDzrHX+0+zBdq9i4Smcc
    postgresql-postgres-password: AgAsFHwfvNOYpVxryyfy3aYUx7hK13jr22RH4eWNQKclcKZ30Ccgie+2fWMYtQ7b4o5mx/LFjuCNv2qehgKjqQeOWBw4dY7x/jeDolLfD7t4gcyPXKrJtPVNIWG3Aq+08osUn/daigGMnolUrENBtv+K6hIFECUJZatUqdwWVceK5+32qYKQAyl4FEAz5SaZFyQ8kMyB7ETuA7f2ekL+BPlZs808NCQnF9ATj6Uxfia1PeST11UnmURKph5SJwDU+85H3AjktLQ9JUNC1xCuoR5WbaSzhzAITRhcrVNO1ovrAx6Nlu1RYvFKPZwLTpDO6EaLG7NJdVgYlqXT9hdhYvWHbN6zj+wb44/LoRZS3CyZIR+Q6NPnL5CIF54uMvvXe1Wd8JB+y2DCvp3vN5ogfOdplud7Ybxp+3TWDlLmDs3u8VkhsGQnmkPQBJ0IMwnzhSiZvn0gRQ7dWs+KOq9VrXvqN6q3T61XhM9x1xda4vQXacb8QNyBzF3DOUmLfdNZkl/gnVuv0f4MbIfwV86D+J5UTprkzRFq7ObWhfMKJj3hKOdTpLIOZYoD505yIcsmEYJz2PqFyDmks9L5BnQrDs+qzAB1JfGOlbkuMHxHf532m9o9sERZrtt3C0oJIHzcb1rZwwCMMLbOM9cGPhEdhZjebJU48UDwB4hgvtOAX9F7Fw3rcSv54GUrkfpS47PIim3qUd/Bghyq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

