apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgAK9SgM10J6lpnBCXdcTVOBlTzOw7Jo8oz1bUN9HgSg2PS1qOqtsYv2d0AITjjg2RmoNcBzEGNdhHQUxr3z3gCef9WLFhr6/NCmIDVaOXOAr7n7qYGh+A9UsAiYb89Ggnb/MCwnpuCrc5L86VTB5tR/P2kj5r3ZdzR2s/sX/um174EhR38FpF8oeTH1hiQrNnK6UAkqEjStKINJVwwVRftCVfCmjrEl+zCR8QkANnm01pELZ09u0f/EDIe3X5qTOv0Kq0wBvfb9B9BDfkPg+j8C4DidszcFzwP/1TZ7UJVXnJtEJmblYchtG8EECvAeICPDUu5RrPjiNKaDjyPpbGcF7e3IS1BwXlG1SjIMZlwRGTLRzPXOv4W8YQlSc7QxieI6n8kEN6tVpXp+IyZ3cwvETvr0NNokfJa7lbrX3z/K+twIgOsDmNnz+XKaUNS7F65oGQnJRS/wpCO/gNVo1k9vdJik1rbtuTXGPF15ta5i0Jtlt3/ofA5oPlNiuJhv2QaRzK+tmqh0yJ/3TOzLMaaq1eivCk37TpnyUY5h4DyG2q7LTxg1MXIlvopRDDo2KG6idO2DZo2ZBCXZvirC5JdDao27V4SiLl39GqW5lrALIBdD8nTYiG6RBjYIQf35Wr0gSoodLZVw9XJiAihMPbIpjZ4usE7ijvjs7GNwRd01+cnjrQi0mjGkWvSmIen0DfeSLPcKb1LYXdk2W/c5
    postgresql-postgres-password: AgBFPWaJHVwpjELFM1VLBg1qUu96tu9WPHwY2Ep4NTEx9FtPpta59hM2HV6voAhZiDyz24xtrmavXa9q7EQUIFugR2dx8kzxu7Kqdh/Ol112wyRpGBewSE5dJqVGg2vSMbXordvP2JS5jNiaMTanca/AwpsR4nmK3bW54L7rfF0xo7ZCDt5umMNwgnT7D5TZTOpk6AFQYKDwJgoy6dOlFcIn52kQzrqJzEwnGJ9ZYfBwVFvk9JJTK7dozArNcV0pFiJM/eASt1LIrgITzcygansHt9Hkq1+nX3wNMz10aq4483tvM0xXnXNfxrL8qCM8dmf1kNMSCv8+ssnGiTV/ZEc7/NC3jTW0niEYcXnXoVKrumNwTLk2JPzzJJn5VogK0F05rpDSq1qjIht24ohVOSS0AmzspECY63qNGoWCsrv+qSnRJvI6vq0tPy1caCQ0pSDYtohR7j2+MszR+uWUw2StL5+Q8z7DAWrcmGKVVhcVXGMzFAncVdx2l+qNc6bQBSEcbcfOT5Jc5JF25zsDsf0uAh00QoNEXvx4P4PmYOA1lJ8Uw6XSBST3LTOxu+bNauNe7jyXga0ePYOl9lDOOL56ApEVCC8p2vNHoD8obYvHBjX/lYPcWz78Vbmi4zFilZWX9NPYC83Vch1geIwwPEAVFXgWol9HUvqnpm42XQ0a5lEozxjcBFwCfn1ATLSx4fl84Ha1VXiFrpiS
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

