apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: demo-argo-tkc
spec:
  distribution:
    version: v1.21
  settings:
    storage:
      classes:
      - vsan-default-storage-policy
      defaultClass: vsan-default-storage-policy
  topology:
    controlPlane:
      replicas: 1
      storageClass: vsan-default-storage-policy
      vmClass: best-effort-small
    nodePools:
    - name: workers
      replicas: 1
      storageClass: vsan-default-storage-policy
      vmClass: best-effort-small
