apiVersion: appplatform.wcp.vmware.com/v1alpha1
kind: WCPNamespace
metadata:
  name: myles-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: myles-ns-storagequota
  namespace: myles-ns
spec:
  hard:
    vsan-default-storage-policy.storageclass.storage.k8s.io/requests.storage: "9223372036854775807"
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: best-effort-small
spec:
  hardware:
    cpus: 2
    devices: {}
    instanceStorage: {}
    memory: 4Gi
  policies:
    resources:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
---
apiVersion: vmoperator.vmware.com/v1alpha1
classRef:
  apiVersion: vmoperator.vmware.com/v1alpha1
  kind: VirtualMachineClass
  name: best-effort-small
kind: VirtualMachineClassBinding
metadata:
  name: best-effort-small
  namespace: myles-ns