argo-cd:
  configs:
    secret:
      createSecret: false
  global:
    imagePullSecrets: 
      - name: docker-creds
  dex:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 15s
        namespace: argocd
    env:
      - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: argo-workflows-sso
            key: client-secret
  controller:
    extraArgs:
    - --repo-server-timeout-seconds
    - "500"
    - --status-processors
    - "10"
    - --operation-processors
    - "5"
  repoServer:
    replicas: 3
    env:
      - name: "ARGOCD_EXEC_TIMEOUT"
        value: "5m"
  server:
    extraArgs:
    - --insecure
    staticAssets:
      enabled: true
    ingress:
        enabled: true
        hosts:
        - argocd.tanzu.blah.cloud
        https: false
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-live
          kubernetes.io/ingress.class: traefik
        ingressClassName: "traefik"
        tls:
        - secretName: argocd-https-cert
          hosts:
          - argocd.tanzu.blah.cloud
    ingressGrpc:
        enabled: true
        hosts:
        - argocd.tanzu.blah.cloud
        https: false
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-live
          kubernetes.io/ingress.class: traefik
        ingressClassName: "traefik"
        tls:
        - secretName: argocd-grpc-cert
          hosts:
          - argocd.tanzu.blah.cloud
    config:
        admin.enabled: 'true'
        statusbadge.enabled: 'true'
        users.anonymous.enabled: 'true'
        url: https://argocd.tanzu.blah.cloud
        application.instanceLabelKey: argocd.argoproj.io/instance
        dex.config: |
          logger:
            level: "debug"
          connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientId
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: blahcloud
          staticClients:
            - id: argo-workflow
              name: 'Argo Workflow'
              redirectURIs:
                - https://argo-workflows.tanzu.blah.cloud/oauth2/callback
              secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
        resource.customizations: |
          admissionregistration.k8s.io/MutatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/clientConfig/caBundle
          networking.k8s.io/Ingress:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs
        resource.compareoptions: |
          ignoreAggregatedRoles: true
        resource.exclusions: |
          - apiGroups:
            - "velero.io"
            kinds:
            - Backup
            clusters:
            - '*'
          - apiGroups:
            - ""
            kinds:
            - PodTemplate
            - csistoragecapacities.storage.k8s.io
            - leases.coordination.k8s.io
            - endpointslices.discovery.k8s.io
            - events.events.k8s.io
            - machinepools.exp.cluster.x-k8s.io
            - httproutes.networking.x-k8s.io
            - tcproutes.networking.x-k8s.io
            - clusterresourcesetbindings.addons.cluster.x-k8s.io
            - clusterresourcesets.addons.cluster.x-k8s.io
            - challenges.acme.cert-manager.io
            - orders.acme.cert-manager.io
            - installoptions.appplatform.wcp.vmware.com
            - installrequirements.appplatform.wcp.vmware.com
            - storagepolicies.appplatform.wcp.vmware.com
            - vcuiplugins.appplatform.wcp.vmware.com
            - wcpnamespaces.appplatform.wcp.vmware.com
            - cnscsisvfeaturestates.cns.vmware.com
            - cnsfileaccessconfigs.cns.vmware.com
            - cnsfilevolumeclients.cns.vmware.com
            - cnsregistervolumes.cns.vmware.com
            - cnsvolumemetadatas.cns.vmware.com
            - networkinterfaces.netoperator.vmware.com
            - vmxnet3networkinterfaces.netoperator.vmware.com
            - members.registryagent.vmware.com
            - projects.registryagent.vmware.com
            - registries.registryagent.vmware.com
            - compatibilities.run.tanzu.vmware.com
            - providerserviceaccounts.run.tanzu.vmware.com
            clusters:
            - 'https://172.16.74.128:6443'
        repositories: |
          - url: https://github.com/mylesagray/tanzu-cluster-gitops.git
          - url: https://charts.helm.sh/stable
            name: stable
            type: helm
        repository.credentials: |
          - url: https://github.com/mylesagray
            passwordSecret:
                name: github-secret
                key: password
            usernameSecret:
                name: github-secret
                key: username
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, blahcloud:k8s, role:admin
    additionalProjects: 
    - name: default
      namespace: argocd
      additionalAnnotations: 
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: kubernetes
      sourceRepos:
      - '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      destinations:
      - namespace: '*'
        server: '*'
    - name: cd
      namespace: argocd
      additionalAnnotations: 
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: kubernetes
      sourceRepos:
      - '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      destinations:
      - namespace: '*'
        server: '*'
    additionalApplications:
    - name: bootstrap
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/mylesagray/tanzu-cluster-gitops.git
        targetRevision: HEAD
        path: apps/bootstrap
      destination:
        server: https://kubernetes.default.svc
        namespace: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true