argo-cd:
  configs:
    secret:
      createSecret: false
  global:
    imagePullSecrets: 
      - name: docker-creds
  dex:
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
    env:
      - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: argo-workflows-sso
            key: client-secret
  controller:
    extraArgs:
    - --repo-server-timeout-seconds
    - "500"
    - --status-processors
    - "10"
    - --operation-processors
    - "5"
  repoServer:
    replicas: 3
    env:
      - name: "ARGOCD_EXEC_TIMEOUT"
        value: "5m"
  server:
    extraArgs:
    - --insecure
    ingress:
        enabled: true
        hosts:
        - argocd.tanzu.blah.cloud
        https: false
    ingressGrpc:
        enabled: true
        hosts:
        - argocd.tanzu.blah.cloud
        https: false
    config:
        admin.enabled: 'true'
        statusbadge.enabled: 'true'
        users.anonymous.enabled: 'true'
        url: https://argocd.tanzu.blah.cloud
        application.instanceLabelKey: argocd.argoproj.io/instance
        dex.config: |
          logger:
            level: "debug"
          connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientId
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: blahcloud
          staticClients:
            - id: argo-workflow
              name: 'Argo Workflow'
              redirectURIs:
                - https://argo-workflows.tanzu.blah.cloud/oauth2/callback
              secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
        resource.customizations: |
          admissionregistration.k8s.io/MutatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/clientConfig/caBundle
        resource.exclusions: |
          - apiGroups:
            - "velero.io"
            kinds:
            - Backup
            clusters:
            - '*'
        repositories: |
          - url: https://github.com/mylesagray/tanzu-cluster-gitops.git
          - type: helm
            url: https://argoproj.github.io/argo-helm
            name: argo
          - type: helm
            url: https://charts.helm.sh/stable
            name: stable
        repository.credentials: |
          - url: https://github.com/mylesagray
            passwordSecret:
                name: github-secret
                key: password
            usernameSecret:
                name: github-secret
                key: username
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, blahcloud:k8s, role:admin
    additionalApplications:
    - name: bootstrap-cluster
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/mylesagray/tanzu-cluster-gitops.git
        targetRevision: HEAD
        path: apps/infra
      destination:
        server: https://kubernetes.default.svc
        namespace: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    - name: boostrap-cheese
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/mylesagray/tanzu-cluster-gitops.git
        targetRevision: HEAD
        path: apps/cheese
      destination:
        server: https://kubernetes.default.svc
        namespace: cheese
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    - name: boostrap-quake
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/mylesagray/tanzu-cluster-gitops.git
        targetRevision: HEAD
        path: apps/quake
      destination:
        server: https://kubernetes.default.svc
        namespace: quake
      syncPolicy:
        automated:
          prune: true
          selfHeal: true