apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCrTHIxUcQCOQ3D7TO7uE3LfN7M3K9KCP3WJ3sHWLBjHF+ARifehWSX+jVp7MGM8ir503JdUotP/kQxZgrPRw/XKNCRy3c2/U0a0u/+BHoFLIi/In1MyhRFginK+IBCe4kQ0Uj4B4xboBr1CCoPLslLhBBc5qH/2yPu/N5DgcS+R5sh3/nFLQmA+NTZbBr49NkuYdtkp51wdhqeHdgldBYxt8OXDyHLBquOp/r8++VwU/G1XNeO0lY0JEGxrxlqlFxEG6GxItE2piSKbaMk4nL/3igAPNKGvDI57crSuMM190BBy/vTNdEggKHY49LJ0OgQK8COrstG46fcxoy3d8q4t0gzHsgFeD8D7c8qAZOEIZiXCeyK/BosElRscRMSPKdKD+c1BDD66HCnhLEDMjPUtTOBLPKih8CT9ego0OS1bSZxvQEWwIz1Ap11QrX9VDCZneqB7Cku/eCO7aLzUc/9exX4dZe5YwcHMRjdZMpnjpEEd/5VDVkpFnkWn026GwbVUkAJXG10IRNpUCcMWNdYBbS2wV8VAQtUYChHFr1IXaLVWSewGvhhRb+LE475JkMllN7hECZyaPnrhmF3puK/rLWPuBomMvhCiRvFRCEQvhPPiniBI7g5QJkT3yMLJOE334Bb+OqIqalRv5SHSdDsUfiVrqjr3g45jglf5O1uBm4HYpN2c6XD5RYMjfMDrlVvFiCl2YVXG5LQnobaMTJ/rtO1NLrzEVvvMtElDdoMFcFkTtyUDJcb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

