apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCCNqZ/Zu7LD9/8F5rTCQDBy9unNLhuvdnhGQedA/j/BSvn0D8SjzaEMmMxb2mjksy7eK49+Rt4JomM4YSsbdHXu+6D7yXRLxmgtXHpl/zJyEFzFbqtMrX1eBq5m+9JBlc5DLFGvcR50pRP/LSnJ889arbJbIQgHd0pI7bNWqXofpmf3ikeyu7uQ0UYN0o5EfGl4PKaWlrTguudg8yPu6rwTuDZJcNmlLarm5CkBfetJR38060l08zNyDdCS+BEKyvY+Ejk06nKJmEQa3QMzHGbYD/cCpHS+BXeTYsck1cnLDd+k2ZS8x8A3NFxa41CS2qV+CO79MpC+31m5Ktzk4cQZOiWII9YEyOiQQfCrOioYB3sJzROufSliIz+tmcUGrE9I/4df8KVfpPbo0ZKP7eD+HsUfcMMJOyseEA8VZfnIBrwqzGj3aRUpd7oclFSh4cPAiZo+6rpv/tM1WCimkFgy+cxVW9g5tBhrAwl1rt5F66CTk8fQ+byK+m3tESnmSQ+aMQ5v2jIKxIdhV4lgkk5yUrVr3T0uD9pW2lRTfhuBOdEdlbGx+hOJrGk3MtcR9JqZH3p6iRlvVKNOVsXstGqESvSFpswtn+1S5b6Qy81wEMwt/B04EKchb8iOHto2wizKREKepKpskIJ5xw2KjfmyaFW5BdNWxriKBQgV9a9FhxaYK8DUK+4LrDU7j3RAPW+hjT2sofnUgd67qL9iW7TgsGyW+XWNyb7LSYr39Skb4woYS6ie2hw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

