apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgB+g2P9VfS/hDRnVajU/RsMGDckOPdqAVO8cYQ9He6cZPI4Pf4heq7+cAzHElGS/MqyHSoJHRHdx2x0M69DJoCXXC1YiK/X7+u3hmiP6jItusRkLMendYsG4sLrdmZog0tYcrF9fD8FHSuGAq0jJ0ZphkGpx9vmYWdjo4sEfCrBjSRwvOoE3CgZcJNu65ZfZXIjJ7RSai0JTfeDeO7n2iVxvZvjvPO6HpzmULpAme4pT4UyojA6JFEW2uu4VmJOiwzaRY8hcWyoQx3a6jaUcdCHmsi8c1qNB757+svup/2yIC+9sDi1yXpBFlxEfNphMf1xNJdrzlgWfSRaaGklehpYtwD2T7Om1TidGpB6eznjpHJ64E9+PpR5gT4b9ITW8Ggsqhdl8YB2gCr7lEVTgHr0HYUIDHsooKpZ0aHGY/NWIhCX/6gcKC8HIeMqJ/MXym7MduqHQYWqtz9Ch/f5wTrjBZOHFJIY9A6nchRnY8CygBqecEHbrJe6KMALP7z6C8RNbYTtzeXs036D6lEFehhZ6PDBlhcD6S7EgwGUBZhgzH9j32318ZWhWJIicIfueikn7R9PTav7MYcQnobagTqiQlv21rE4wsI6hSSlYSve66+mU7chs7EsefO/T27p0mf4Xzw46M1J2YxXp8LeCUsV/cxVolJeeXFZ3T7ojwJAzr6u3mdhigCieGza+nTKjALTPtQZQT4lbkO2S1HhkX1uAL4xPRUayZwvOZC82e61RphkGRwsu5cn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

