apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgAyfE4mswO/Hmb30gsOF7mwJ7LGs1VQm50A/W3p95Rx5U0lCg5rAyKNX/ZiN/W9Q9RhBfp6t2KvlWhGILwGpAEQpLId4J3CVpf0ARx2Vm4tB3M6Da0Z4FtndqolALdygh+71XpC9L1iSLoA+HnrZ/J5y+gFEPiD1oPHCBB8A2bz5dIXlEGNbqx9YpTBWIDKhSEGb842JlNWUepU0u5G478fmSMTgtnvdGU7dzzXLXe/5NbPySfyo+qSGakON/IyGQPq2Gmki1Cl4XT3JjFVlGuV5sfqsGnfcZniGAJkAVNnf2yrRyn8NEWUjw6uFyfXr9skg6DtQvE1ye9/jj45j1MjqtO5p0dOFP2HQXvoLtF7HhbnhwVw5/GcJYQdaqnDH85KyY6GPb/LQy3ykulfMPt5mXSuhW5CZSl8qntlwbtI3EaYKzjFicxhUS/RvsRJsgqsG7GqqyquVclQzR7zAsu59lJx3OTYtYXL1dH458a9iJGf7UfdZ8UPL2IhJJnbucojm5DalVUrNzZGLeeaBZOQcIU7tYXzK4689qbjIR7/lMp+fnYnv3lmYK2E9rcNh4dhT+erSSFevjJ7/N0k0WZ7b88ZdRH8XtgbKLtB6cRBEmXyzFf6oge2XaKcShIqWuh7keBkNp7oySdDJtanSVVcPTolbz4AWP5IxtvTJ8wHc+WlwmYef9q3z0hvhVGT10nBXFrPrcJ4qtU2vK2OOLfo/Hbx2KTZU3eNNKBu4czr8HEqDgNCzshs
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

