apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBzUMHY6DDAYc/TV6QN0oHgw/BxCWlgakq3Cac7Iubr4zhDw1cLrazeTGaS5RsOmw0UlCJ+JTx/94d1105QFEuVqDh0ijl9NV0a6yNfMlmHLBkpUio9RsRZ3ogiBOu+wmd4jz9v2At0/LMIsGswh0hHJD8PGStqHzQhnZ8Wk0C4/BpMV2FhblJKBRlzT0klH5hNgA7dNXOZ5k5qlLHHX0UUkiarWvj20WjO1e2sEL7xRiEKRPC4E85n3Zk/jHbM8TuUlXXthGG7uhxHhZ8jVBJCs64byTL58NggjYtLxFOktjJCLi7XI/fdZ7MipRokGKd+59Afyr1XI96NAbywWg3U0CSAD1c52gAlNgIWiKQcxEweXciLSCpbyjfPb5Mkch2ot1tLh5dNHbI5ZocBGWAMrxWbd1gEp7NrAWXkozg71cq54fOL4hs26qkhmovn0CNCozm4OmFwahchvb1NvRW8a4ardzzlWFb6bbCxy2RKhb1DNqQGUsrBMeIP8YZJDuSGh/tLrKEHRYxQ9duv9NDZ32Aaw9D3Q+aXMNttktTUYJq7hEzAWwa4LhSVaUKBsVvuwUsA52xCgJtLB5LsIHBroqFCe8yNGT0/aWefRymwQZcZflGKFbhM5cbDy1wH7WOxfGKVZJfjbn8QS10fptExMPakzCX0hMAQYGiYhsgcfS5mehRorMi0iB9Qp3mH/VVi9ji3Uxzhu+mNqYa6c2R31w3pWUKDSVXID/TiCxuQrwhbMJral+ST
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

