apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgAk6vkXPGjzj4tKyfZiaIr4NdCErqxIDlSIM8zLPEDSfAQTDjvnEPX+EzaI5IvZGH8+LHvdITgX2UUSzU2IX6LhHxDGIlwBAro/K6lRQ4bOtW7edWQKb2QtBBN30guE1LkVDopEkoh5jzCo63oIPhfuV0MPZW0+vczsoVmbsa1D0OkheKKcYhwbR+v0VCxV8WZ0UsPZfjXV0AHp952+hvAngMZOz9FQjXvsQylSk0aBrtzNF3ajDFhorFoy7+DjtQUaJ9hY9VcGuia2AhdD5xFXxu6LaUhvkHqhHjhzvNM5Q41ahl7BzlNcWq6qb4hh7iG7uSRIjkPrGjGUHCAw2o8FSH2yy8OfBLCUMsCrU75KuSQwPOm695lSWReyX3hKJ4xn+K4jEK/iu+Y1IYj2JpEzWXn5v8TVvq8UkFTlVp1il4x1GBaTsSWWZxbeOWJZt39Qj8HOg6zm9WtfrUuLvpUNEKIyDU22WETDR2eBKaNfHtqJme9MHlOjCGrRB8EaRJQMzEAJe9Kx3iOyMiBBrM9b+sqqad4C6oTeumnAJX7AJIyk6V3XBXhecz477+gbzPqKGaXdsmokSo89JXTsspFopy9+wJysGIOT9js0eJlXuwHN6t7JIwGwP7CkRKoHCU9nYGzJvCcjn2ygaCtWyMQ1RJz5YeCgJXErwDvH7tbyb6ZY6e7WaIF2YLOf3B+OfXqoFeN7FS/tRidI9OfKBfcUI8+r0kakiEPnMVqeNWLnrVJNzEB+TRC9
    username: AgB1FHlNd9G7f9MM/4OYK/4V440aRt+Zw7LXobQNNZccMSsTRPiu+QvWMtv12fV74A9+IxqUeNlFur3lofGO6PSj85ymPf9fS8KSr/gXS2jFGxmrVdk3rZEplWpAoKP8WLQuQFZ4yHquvcxaTgi+6EcO9E+1vAbVLdPWKGKgUfjyXsj4Ro58cTdiqawCRPuixSD4ft8V38itQV5/LlMDZAbH/S0FKFX6btz8+qQCLXUl+NDp3+bdxbJM2JG2pV31MNF9dqEz0+asymRNaeQU1nZ+4IqvrByU0mtJpRGCBveI8i/sfIb6VAacEQBgJqLaZP3Wm7ouDIK5CG0k4flksm5/NgDdkYbFrzBZF8qRoMz6521SgK31OZOBUs9GosVF87q0fywC1DEIBXGsYW5gwr7wk/KW/gPW2nG39ef9yfCzeL39LwR3OP+YFXE54kDYWMM/1gTjQ7Oi6X5n5w/67Dh9qC9sXJ+7qNTIqRRF1GwMUVGcNNcr+3rrg3o9ImMsKgZzFPIbN11uGEEhOmCcy8KB0JTZz1+U2yFU1VtM1muBsZaWlIhZsYRT7dCxYrKJTT+OS/iDKcbeTf1JFGBewh7J+SwytL/WmFE3fKlcehfzrS4PP/63x+HitjBHmKErHkIMJvjNRsjTkPVurJdMFP5EK090DvcYKsRLa7iO933Ryq+1vtw5UYePXnzm0IuuK1zYNbWGqVNLj9Y7
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

