apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBle7Q2ALqFfA8Prxx0vsKfPDaYheU1rsfYFAxXh/T6S4UUNSDb9RYckjoV3hzGt+tqbjtsEP++lkdqGdyxPU3RbrhC5cAr5PlMIMBjEVVR/ICdjb2dBet/LcQINNn1kmhJGtJcujb0hOTbjIrbW5ig9Uw0T6Z/Da10xtCxoCMJHN+NXkICl+iHfFr8UtZ6kAXe711qC5178iO6VnecI+nxrLUIW8ovYgCKa8Ks1SOX3inHyA7PkdD++3pChp3xRRpw476J6+Lv1x9LtEdvnSIkO0PMdKdq8mT1D+RTQUCoNbVbQcwVpUu3+ngpwzIDEyiCyAKkZCb3nU8oqPooubHnxgQd8eOwgHk20V8P7aQWvjuCRk+03smWq0UKueMQW+QriLEQFJLfu0IYw5Rh5io+70RKMXBkIWsNLwwZ+CoqPeBin8zd697rdY7CS48zAfChuYqmQu5HsI6cSvnC67/eI3Ysmi0Bh1AaakpCE9nKkJqXJaTn9HFj0+Vf0JWlqg2pb5VoBa2GDaCmvSblFX09jhRfGKLNS5za3tSF4gK15qZNX63fPEdonkImBitmTygnhgLab9TsRuLxdNi9qM3Yo6Uf1s2elsTw+nr5A421hPQu6wsRZRt1dk9X4CMfC+EQvCwERY+xUGBX4HnarZlcHSIOfCRkAV13T2SVV/OdHoo9VOiq6837qqnEcZW9FXihE8aDLLvxlZ0nt66YvVe6sUOOTQCDucnqXhXCv3N29uV8CZrNuivL
    username: AgBk4DUdMU5tLpcbLwOcuHuQ/IEF4d6fWNb2F6DEYN3OmTg/vBZ2JJXG9hM1+Mf7kWUaaN82NZ843Fj8A1YEqqEiqYTrs1mkX5f4U6ho79QT51DOMlriK4/l1l+LmlU+vmVEffpKJsdZ3jyWxYiYmfeHr3Dh4sDe3dXi+kFs3CcAVpd7KjGNEn+enqMrKbe++xo5jVJiQMcbzIG5srO+5533RKzrQRrhQ64LOFwlfiBpVgOiElMWG6zvNm0CqJqM7BflFZ8cvtPxx3JCJERrTR0fHGW3UL9rFOLuz2yPbedDGWTafSzNDxGBCMLFEAMJ+lM5Wn8iqIbsxHMaddNI6Cns+Wo17GzOoxVDTxV1lRGw2pYVocDctII39oqtnsPdsKcRW4xJKep4Infj67/fpKGMHaLsseRgfkMszLkDnEttJb3RZyJcqXgYrA/u3ALbpmvlyKNZtwpZ1us8Tqmm3HkkVPoRA2/rVnLwmlaad6nRhQXpC/ebF5fl9YoZncN0QjuQI4kiCaLd1v0pDJ2BRtO7eYSo7ChQMx6YeyIerG4pnh7MDtsJKJqt/0/3TABwaFG237mEadNejMfsk6f7O47ORZe3+nacejGnM5iHKdw3wuyPoGwQKpLtbIwqTRJGlpfT711B6Npzyj/hJWYWiDmXAsHLA0Mh5IR0y7DfnUU/CG4WjO5ecXqDQZKHs/sWrysokOHSqtI/dium
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

