apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgCfyMt64aDugoVBjPxHS9Kufux6YOs4ZA1gKccjj/ZieqYT7/WmuL8XM9l3ZIxpxh9vc8sCafIGzX3IiKo2IWakLuSnywdDPAaHfEpslFjTRJY/UdFm565B2Kt0eoiDtqzkyhp+NhOHh4XE+s73K6P9Z80FwNU4BA+hJFjTkz9HzgmakYRi9RESPx0Vd3mg6knAzc4ifiZlT/b0Yldr5L0S6ih6hRwqgrVIC0ig1p9WMOCPIu2I3E3lJyzlY+M6DVOaey4H4384+y/nR+QQjx79y3JID6vBww4WfYVCMjzbRB5XT7P0JCfUN4xQVlygQY4dabngizP9LHcE5PWZXduFx2jVGdYScqC8HMBW+tvusyOxMKgybtRO8VauHJ/Ti/ihmc/518H3bkVGr1z/MgZj44uTOwkX0UL1l+xgP5zKQnrTDlcVg5okT2FizK5YpADKRRQq8yEw6ajkMUEk07cU6rRGRH01orny/dbenzioQkmufUYxLhraE4vnJru9YuZQXpczkxPuoDydd0V4UNvWncMBqgnmEDfSDEHetdzKukHk2J8RvyJQxnnb+VfHPepba/j5ZguC631gMtREau5HdsKhU16pMw6H1bIGkGH+CN9ws+ei1ZgPeGndf4GXaOxHd8AhqU6e6RBFeXVK/te7c7SynsOLfA8Ws/g8LRIDbdrVx/5IJayzI6XKCSDvV8QUjudqvIUK+t5lA5rOB1MqjTbXQ2YICwAbbQfa4Ge2PI7mvxkYCqjV
    username: AgDJpFhbMtdLODQFjy+4sMAbOPwbN4eiY8LUhJzY2LB2+ISrMzNaD1Lv/vRQC/ctVnQR26zY2GiehtX+wtGzY7RqV+ljzDQphHO0uQ8XJDmwwGUpiC1VLUxwo10kyVElhlQEsvXsVirr3I+AjNUsYAdvhSFZvk9Uembcji7FxOrWdsfIwvO+OAQdCygbv+ifTlO46CjOnil2vwWiyOmWJIlu/pO+MSsx91dxJT3HTLDpa9DrUWmCdHnmteU4nLUQ2Y8GTQraJlRdL/QxyQzph0j/ox+RMTVjVY5XkCx0/L97PxHKXcs/EwkltDEY/k3jGyWMaiLSJRM7PhoK0H8Kp4HZLIvMnYCdn8jg9yV3eArkCYOSKRck5FrycLadHQqk2bkpRpU/c/pLvgPomv6JMftbmcxUaD9GSihP45SPt8eZaR3l0C5jNE2dhm5gpT731wfy6XWc4lFvfQq9Ppulf/X38sVCP12263NbyonDbtVjR3vecjLr79wUncqey158VWJd2D8zhqWCMZmDKdP3LCBev7zmtpD/GQ5kG6LWaGSzU5im6CVhpUIKDFjgb4dH5/TgQDKXnWLKCVJerPdYpxFRCiiQ/cEnFhWvwD/GsosWizFrvRvge4czRMRmee4Y8HVWEUXTBB7C8RjdeM8YMF9YihJV50l2os4ReNuEQDvgJlhEmRBUq+YGu/L16RYRL2jNusqtlOyGImof
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

