apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgAqOIzIvrUlKaiW16r3zBOliFZQQkhvP8ynINOeViGaAypnaoq7BQl2BbRQIn8H2NJjEkUp8H4uVMDxZQGD2FjVTEF+UTpd4nIDI8RTluz1vy3aW5Kpf/lmkRvNtYC6f+Z5BFZKLFqy8kK3c/yRuPJH9teLek5lB8SVxSq0Rxqlk9Ky8qb9dPLyEi54jO4QQBHMZmb4lu6c88Ug19gwvK6hWAKsOW6s+XXCv/WRhi1nU0ChjQqkb9uErjgt3wMWiNGM9ov/f4dDB/UtGbCNhl0fj+BKig+yf0Ph2BtgGTusQ+/4ke8c99djWOHkfb14Sgv3eED0kdbMwIUi3ANUwMzZXda4Am923FdQJZQh5qdl0HvPVJjOrFfxJy3utm7S9Q6qtg18Ig9lVwJXrm9TdPPfoZkXF5Kl08wXaOV8W3Sf5wj8EdpeQwQ/nlvjOoHHOIVAhinKVzz7idsWmFjfeX5jIdb21smnTvMklGu6uyy/3B+e+OFNa9RQrwH/IHvCKwoUVdieFGrxnBg/JrlTasD6MibR2HjhdUWyes62XhdqQfZyhLRTPg/NBcf294P91G70QRPEwPJ1t1TxocQhNTfMzOokarj3aRlzdfhimtOqQiHTgdekuvz3Qzijz6yZIWvHYYB0vWRXmNDpGUQS/mynCv6Jeux4ZjosZ9GlE3744sAWtPg8iIeEqdIZ2y67/t3gQdjAGnYajRaskAwgG2isW7HkopxdnXDt3e9+nN9rtiGw6b/8kkWF
    username: AgBKvmwLoDE7gkc0lXBMWYYxC2tK70HDYAoXe/0Kinf1IG3qdfa34E7yhvbP85x71Ti4xXemA7c9M3pNOEroaFAgAtFKLOIYj0V+ruAoiwQHgjkADTPMVNVvMhmP+5Wj7BzX/A305Vj5Zn1BGBCbvpOcWtrwmUxAiOD5GbHST7aYD45us9/X6hp8HmjC4G6Dy8jd+F4D5Ff6kO450mKU2bgsS0iB3/gts7nQYzNNK5BzLiM6O87yJH2huHoas8AZj/1nlKOBjTENJTJvkfaZh+/kCl0ulGLtyxOt5ZojtlFZVjpqhGTOW0WRD8+7aZeXnDk2rQsT+vs7IfL5HxGAvsOXTDlvnYBZ6+pQiX5HLJ/t/nrv2grykGc59b1JJL0VdRO71LC0pjj59Dkv+dWlImrbQtqOwkpSbhxxXOZs8XsBqEy3MMVmMNJTYw5DNbBhMQZ6oQqFFxvKfhp6Ryv4J4YZWmUNOx6vHuSOXg2g5Vrdgw5qYiVSJk2WzclTKib4Pi8MvuU7UxsxtWHnv/usJnRbSbqdmrwGjgHLMORU3CLJ5qF4+4kY3OibgnzobYqRBRp09T1/r4CHCQSLCt0ROb9c6q7jxp3+1SY5szb4rLhrbWzifynSDASMQfoOku/Mb9WTmPf4w0sbiaHHC5KzNwXiPsp7RL+LZqhxsW0CxKZY6Sj5Pr72EGm0nCa02DbYvlyqSC+BuCT+pyXK
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

