apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgCS9RlhECnhN6PhfJZ/2XLhYFuASeAJcuahziN2dP7cD8M765weJDc8wsdLsdZegdIUOvBQ/039c6wFp0b4GHUbgzBk94YhH7CdI5VHTDDA/6XUc+XXmQC0ze658L74q0AA4bGWehoYmc5iZQ2Men+WKLi1Nd2V/w0GRQTJ8fbtQX0fWx0IGP3k0YewasalfIzQgIfHXRhVOtpK4k81eFR3h3Z+kxhnyDdZrEfIeKY/FQw/4ShNyXnyDSlzsWhY8VNeTSHY4J2DJ7YyUAfg5Lw34bskzuaG0K7erzxLTmQTjnFyC1TyFa2lkRnPbVbvwthlL6v1mIvBmtxNHxzJ8vbbmZNQ2RoJq3XDZf/QHVucuqrSBANUayQOqCcyiVfo1gAj4MueKbBx/bHe1Y9giu9Iseyl9n1Jdnl8JagfXNqBUlFm+nFWaPFH3933SxxTcenzJ2b+FJtj7y8NG+KzlitYLGVF9qjtRa82nCE3/MRB2hFu+WSD1twIKXPkmHgfTyiccbCE8xjp7oMKIxohU7zgAi30Tv1EdZiq1/56YUZIwCfXEP8qxxDhnBlK1HCVcxW6gEiyHdgYt8tWyU3bwT1KhKBiXS09gz+D7AKAY+iRxmaOb8UrHkIIdMGfgZ2gC0vsfmp1PW3GeY3g6PVn81ed2RQvhPnOfO5Hq8UWL8sUsDUte5E175FCQMeE+xe/7W9QsZSFEkR7T7woYn4xW/og+DtbgS26vjzpdW//BmIrghMejnQFokqq
    username: AgBMBNg+VZJvRQVWi+jxgYD5Am+sbVC55tkW4DXqLof5boFSrnmzfxJRI6u77t/8VtoQ8JRoSWfgnbruGA7qsAnT37o+Ofz/zbON0V5vq5UCi45UO6DzCf8bk+RCLXb9w5i5EnfZm8pj1fnGeNAgBdwuYfZFOKxLIOc6Y1IVzB6IHyQFXZYcKYuqPisG6DNk34xEMcxqCNe6Z6ATdxtEeVJieKHf9/ZnQESLV0S307/8JTpMkAAOv3NINGmhsWHxwtinJI98SlcKf5VhJ+jaRTnfTfQ4UBqW1OT4lus63OpOzXrhtfgtq+1au6OsVheJQca6pZZ9+fx0P2Jh0nNuH3bB9Vmc+tWP5UMcV9yE3LjhlxbTIv9ae81G3go+mqBY/6VfE3Z6OTU6JxsmU62pOhmNfD1Jk3FDBSSdd3BoVrh1n7hTFhrIedatnlDQAxpJ/6TBmihuhGeg1gYbZgKXvSRT322CFWu8+qtl3Wcldu6GmvT2acOaGNkPKgxO3iJJ6Vbak5TwuovKuLonwBzKvpW75xnFauyfSfFlnVQ/vGx5cY3UG3syNBAB5nrF3kX1sY+l1PQQ2xcAnNuhdJP0s0VksqdTtulAx4jXE00tCN8THksbAlKnWuO8dvKuqRdwfgYY+AFw/ZnnXmcyD60y/rRVWomBJNH8zlILBBwCMZGZf0u3NTQqiuuJUxpcnib6UHgfevj3IFAxknjo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

