apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBE4AvyceH1l342SJdNKg8R+VK40gme1b5p1DKTDN2IQGFAnWSG8k1qvYSxeyOL/945bfqSkNMiS1HKHQ38piQL2JMi616aRc1BDGiysE2keuN7qHbbJnkwQHGNKFz+TIUfXDNMNDEonA261c67EQXLGn0Rv3r+V1xzWC2J5rhOVFuzCUTHxrp/chVycchlZ5EBjOYagTckXNsxwqAT566C18DVoKFJ2P/VENqvmZBKwhqOolVAnbl3Uv3hIqPFX2/7tqoOO67HltnVksw78UsIHchIot9c+HEwdmPSTRJ6Hph/XBsN4jY8GgqgVC60t0sEChEtG/e9gWybd3bTcxVU21L306McVa1xSrdJjGtLwr2gLjcFELlyLr0ELOYqFdKo5g46wMvqYRe/LhRzfJfpIPtG0LrEQxJsBbiC6mwiAoIKZOlNQ8qTUOjF/S5V4gQK7LucOaDvaoBvxmCg5HWVY2V1KEnBnMGwgs6DnDnxpFkBKf6wxtyrAI3IVOuC/lsyPJ/U3h+8h079yD8gpsZqLSYZuPbFCFReyDkLhDBLsVJJoj61JDAHTfIxi23lMkMXV0v/uQXZNACxSI/IVtBaSd2pGvN5A9tCyXI9w2uQUtzll5tNPfDJ/rqckRbIn4p19cRPWjVJCwS7fLSvtCJxCxCkXC7tCcZfKIxhL+OPbPN9vNh6cD30gjau1aWw9gA66w95k78PLZP/NZWtyFlncf0dY+vg/laZiErsuaahOg23Wf2TYSYr
    username: AgAcUvzagBSeU2kmCNLcZTsHauVbVQlGBolScq1G+lwKmjVUTvvk3rkv9bbSm30p6l5f9wagdzuTgkhQEowNtvHKMrSnk1GMFGwrOIWjCNMWna0unIjg3J09OT/mTFrMPK23ngbSasRmUbS0AJ0ytlljrtM6nyqe+qULBqhGgwdSQ17VIswgzFpH1DRSl2CWlo49AWnia9ytNSP11DTXs0RWzCsTBYky45FFcHlbNRkCDQHwiSZ2gmURvqRX2YzmCTnPYPbBwU6T9dQTeiphDez6raFg1VjU/mAkfQYQTUSkvE2IQsQB/eezy5EfUSuXoCMWItiyg71gbbeWTJDgSumRXQ6bhKXS8mLF2dMipCqLi6IFoz/4wKewPo7O2UkVOiz68y+v6+N8FlEiaCW9Mw1jKGrl0FVpMU1zZfrgiTV5yXN1KlOvqdQCM4H8XtWh2/4SErcd9HRgQp7Kmz8QsBtB9PW3ETIOgx9JZXFHkjImIEHh7xT6l48igOvtPnAtzInoGSi5RrXDwQDxXDzdqxHFsm3ykpcQ/I+jLbhAZsJzx+Nlekbd3ifEK1+DgtKeLMDXTy1hu/4aIoWhiBlSrTat/xgCNVXgfqE1ayDuK2tyErrRNYKKIPlTRNghrZ0GTXyUYvd0BJlLsfpTZSc1EMlh4Gz6KcXAPpSyzFSh9tJP8rQ91aynutN3UlxBiY02qxPA0ypN93JRO8V0
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

