apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBpNC3BsIxgimTdNFflwM9I1u7B0oRThw+S11JtHOEaMvQJS8ukq9d99uXPL7NnIxE5Ttj2cHof4TJhJTo/DlbUBQPP9YEevko06/6miE2VsIAUSLN2TRnjNFLgWO3wGz3yaIz85dpeWH8SX3ZMo0xnj2Ia9Hdxi+W/4ROLA8yNFHAAKTuqRThqqXxriYruEYqk5oTh7bU0/HQDl1/93IU3T5LuNqZ3+Td0bcBFFnlDzOwRegHYGbfuimY28snBzp3IaiiaxtnGnBTVeSMUvHrxGM9VR1tujE2FP6h0Jl7YLgjcbA4wYaEUYusrILYcpedJeAa5W3d5rqUDMeKdLbLhzEDNHA6AwjQmOsAZl7Nyo9te4l6V9u4zZTx7kbG64XlAobEVhqJ3DHwpq0uY79Mrlo4Lv4femM/hmE3A17/m2DC249ik3sODf/HucPDNvRR8hVHMjHowH2Srv+cKxphF9SdVQlNJwa5PoC1SApDWLeOLnkBlofMf3l43+DKvzaLG7QEKzm/gulRuvCSPU39okBSxaEYd/bEhIH+hoR6tN31DgOZNLZYOcJH6pAAkdxPxOFY77IqKzyVSyZNL0E7RqtfJfqkAjSTCWqNXPKtjGeOmYp9rPDCJh2cGnFKwPZXRH5roYAi20hjO2I7xIoklFhwhpzGe6qg9zhabAyl+tIqmNms2xGA5xvUOk3RfhrVB+FQ5AwN8JRcIM6pVzQkxjqspe/kU4NDR2F6QrDXiXPS5C1iX4EZY
    username: AgASG8b4ujSyGxsFVN6QregVh64hDuNhXZ438f1vGPK1WPulvJOjSzNyxruyfc5wibN0DirgqcbznB552hY5OqBcNvRbW0Ep4NyXoccN//TMFkXZ0VEnOXLI6X+l36q6ZdOdx5G4o989UQTkuhNB9TyqDU5IjSyS0Z2SLJZpbGvAaq8J4vUjAApOFi5rz7athhg2T0ZdFQqESjMgsP8okVVJgRrJf303r1aKvHeBxOz46DxtABRkZw1tLQ+IMQaZjwHGYNrtTL9gsN8hqbn5nzwUM2tTB0pVRL/ld1dECCo1RTpC0ATgkIaas8Eu9yUzWTDE7Wq44efrl9DsyZACVxCXqyLgXfClBghFaiHLMBmiDQY76FecOiee4jrBb5eH/kI5wxpX8idQxjphzFavuuNQGUCA/R7h8FbJKDhr/TXCZMeXJrOdughruYXV3q1PQ5yzI5NOypb4MeQUaxfbpWKFvgNQHYsWtm5tgd+37VAg5l7qbt+1pjeheV7Sn2pjha1A74PQa7/x+bmjZbIraSO01PLh6zKoBjaSW37Lzm6aB2+vBCTWWCFxFFmX8ZBLy+rjWsJ1zoVKLVg8I9hQxP6xF6FUMZBvIN7jn+6Lwn9Uxz0WZYUwwho80233lNBMD1vgwDq3bF4C7KNnS0o+rdwmJ1ElIlnHydn2v/Xn3ajKzV9Fbttr+QpmnNK2afZILwIVzLv6U1QCx9Zg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

