apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: manifests/knative
    directory:
      recurse: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: knative
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    name: webhook.serving.knative.dev
    jsonPointers:
    - /webhooks/0/rules/0
    - /webhooks/0/rules/1
    - /webhooks/0/rules/2
    - /webhooks/0/rules/3
    - /webhooks/0/rules/4
    - /webhooks/0/rules/5
    - /webhooks/0/rules/6
    - /webhooks/0/rules/7
    - /webhooks/0/rules/8
  - kind: MutatingWebhookConfiguration
    group: admissionregistration.k8s.io
    name: validation.webhook.serving.knative.dev
    jsonPointers:
    - /webhooks/0/rules/0
    - /webhooks/0/rules/1
    - /webhooks/0/rules/2
    - /webhooks/0/rules/3
    - /webhooks/0/rules/4
    - /webhooks/0/rules/5
    - /webhooks/0/rules/6
    - /webhooks/0/rules/7
    - /webhooks/0/rules/8