apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: 'https://github.com/prometheus-operator/kube-prometheus.git'
    targetRevision: release-0.7
    path: examples/continuous-delivery/argocd/kube-prometheus
    directory:
      recurse: true
      jsonnet:
        libs:
          - vendored
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true