apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds-secret
  namespace: default
spec:
  encryptedData:
    accesskey: AgBW8N2ZzH9Gkyac1MY5keTWuzSZKkeNzA5ylqkZCQHI1bwvnzQm9Tto2QBtDIQUO2OuWklALPU6JHqAvkColoKGdp3gsz4U5ldnU8vrchg1H+R3YP+aReW7SKvkV1MKThrbFvUiYViO8rsUrbpAaZXgnpU1h2osNTCBQdcD9CDRfbgxaViQBMweE3Cz0DzeMLs82WHL9zEg07hwaQR7QSczTpZqc1uMcbdnuFzGmU45eeEYWJBn6QnB2rYi+JdFJXvP15TSr3yoDs6QA+l6+a2CYOQTUaMNuh87pq2cZqMXM3UAZdeTMvLVbzMMVC8cQtpO9273V8gK5AoJxLoYtkGXJBuyU/uXRlixpb9fB9z8s1M8dhA/1wonYvcxCqkypRBVaxNfDCu3QHdSIJUMVoX60Lrxja74GnHquKp4Edjbz+asGF8KdwKQO/Nh1f/EUsDWFm2SQsYaKjo4oUS1OMCbD9k1OKClvxA9Lt7fbrxc67cj008hpCBcxu0wHKGV7Q6DDhj/IawPTzCaHOjuWUViYfkXaBarxTXg+gcDe1UsRidlT1FsB8NrMwx4jbKxLUZG0k21YKwbSLZWOGgC4NpG5Sec7LQM5FeyCT/b70EluQMD527R6VWa5PJZoGOTMTnJAAf0Q4u7YJO0XZve2+p2gCZEPI6AJaxZkuiZ94M2CmGOqwjJp3NJ8TtRoymlI9jgedrB4g==
    secretkey: AgBpqgguzL3d28RkLcc66lU88GWMqe5273jTT+OYRfkAy7OTAJ1508ZWC4A7D14Wyykg8pY4ayKBaiNQmgyimCBdqm9JgEKswxTQ/4MJToHJRhLQCZGihR408kQ3Py8jaa37+fBl4TJXGz1xnDlYKeOci0o5rY6J1i/tKyFMqaBT0tAUlnLU4PIikQS2btWlRF6peALSijNxkU4X7yegEkHuzG7uiezev3/qWGRkHpPPhF1HnGQq1hBiaYBpb5RX4/Gct7Enfv66zTKIxvSDxZkhHq0glIWJO0aoCKv+HU3t+yC8Mi9DS0hAJyyKncNlfSUeizhH5YHMKQap0sT+M51EQ1VLeZFkKQMUbHztO2LzRSVZS0Zqdk6YRRa60xEdZymjZUg7JTAmJoQ01ziPcVt5OWc5ruoeznrY4ogBwz9+LI8Za4ZJ/91L1Tac0mdTmn+YKikXCZ11Ygw6owE2V3519HAc2eIXjNMP9CbPXW4jF3pyEAmKQkI1TtSZ0kawFsTjBWG/fSRMhY5S5j4vn/WEMBANjt6iFVtM52u2eMTGCHrEYjCUofu+3LBJyd2dBbgCgFi7dvTQNbl9lrlmYQjCQm6N4KNjBlUbPhS4du64Tap3vkshXDvb9qT+OnDYWoZe7ZUQdGvvHNXb+nu0DZ70hZBcoG5Fl4pG5kYJRaFjDLVrtzSx9K8l95tG9TXxbzSHtmt/phrhPg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: minio-creds-secret
      namespace: default
    type: Opaque

