apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds-secret
  namespace: cnr-eventing-getting-started-w01-s001
spec:
  encryptedData:
    accesskey: AgC9mz0c5D+ctg1QFIDlIida0t05JU0LcBji5kB23M7MLq8EeqrQWQgKgLUlrOpdVvUQNkqHCUOZ0YQdQO1N/Cp1MvyEsmy7tp3wZUjA5vKVTZ7yYsquxDFAm45JJpk1popPI2UfPev+CsVJ1efPy6kT2wQJkUOtkQT+z0MG7pSNdsQtb8NKBJwGbY2tC5t46yBBADD6FfrUQJXhVr4sl6cLVkww+rx+2YmoOJJw/VI95YBj0Esd0udjIuWV8dcvMdI3GBaLkoA+O2LLoydP1CXpyWbJNL3lGeUmKp68qvTdXoYaeUNIps/FyhyR0dyYA+Kxu+wt+9YvnipEFrEGOtRjG1KoG9XLvms1yCF0BZqASSch/EBnbArIQpdWdH/Zynvn+bEVQ4YPXC3Q00E04Wq94mypmf60a3rwwW+kN4+gghvrk3N4bfoMwuwVhL66S/EOQMKnlM8dCxgZWejC6VLm30sob9fhkG2aJwV3Zz4m8VHiNkvhmjitFeseUdqyXIeSeCL8ZgOEe9UNXs0fhrBPG/J5LF2DVH5cbsbLizpCrbyHj0Km2TfAkLugi9Ge+bfW/j721wPp9EFNPL86VcHMhLL1A02cV758gyocReCnhr07TvznK3gvD4zfFnKMR0HKNmTE1hvzjTy43NKo+zfHKgbJffc8rpwv/Sg6EKqpmtkSawWgYpeqB+UnJV2ZHkCGNMj+GQ==
    secretkey: AgA49cTQo96lBaYPzFF8djZSTVYbqo9pH9pQbhjFGKJsDACdY/PE9bCXCXxb9/zptaPmYJZqBuOZ10GzxqXwF8isT3PmVLZ1GItFyuVqw9z669Zs9P/ZVsdT5kEH7WNX9oIJ58AJMWqn82tTAzZSwYmZMnDB7BOTC276Mo2jn4L4PgCllT+G/ABmSMmQnnX73KfeKcG072dGq8EQyMBAWGKqCRnD+48szIsEG1NzfWO3EIZ6m6F6fsVeM5AA+nkeJ+VQxwgz6Ewn80WynUma4DnbesqKFBXQeEWC+zvRa5TIZPiRAGjSNyJXvWHtgnhRW5KJBJH1b7K7YN/7zfkDhugamTe4M+fos59CSw26a46DG8B3CZOnDlAbHPMM7A6dkPJt4JPxOusFJq75PLSs1rbZyI29inGRuH2MP2ipCVwWo031Dp3HbfriYnB3UjmNqzyunSjSTc+19Bv6pPAai+y63l39E/YwVKICNe49m4WphIoyXcuix2dvXFyQOZSLZnFztj5BEylVbW13kIDp2PkPSmLOjFp9GrpgnD4zV7g8PrrUnaZ0+gc3K4yXaZCLPUqDSdjh6Yd3IxagPPmWKpUJRoqW9XmgMs2fKEOY6YjRzHsW01BUL5zIQGVkJS3bhFxez+W1DW25Sw1d1s9Wt4Ts9UkEBRjhmNjZgz+gs+xXk2wN6kRqnNVzGGLI8JZIhz0Z0VWucExi9A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: minio-creds-secret
      namespace: cnr-eventing-getting-started-w01-s001
    type: Opaque

