apiVersion: v1
kind: Namespace
metadata:
  name: buildkit
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: buildkit-emu
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: qemu-binfmt
  annotations:
    argocd.argoproj.io/sync-wave: "-1"