argocd-notifications:
  argocdUrl: https://argocd.apps.blah.cloud
  image:
    repository: tomaszszuster/argocd-notifications
    tag: v0.7.1
  secret:
    create: false
  subscriptions:
    - recipients:
        - slack:kubernetes
  triggers:
    - name: on-health-degraded
      enabled: true
    - name: on-sync-failed
      enabled: true
    - name: on-sync-status-unknown
      enabled: true
    - name: on-sync-succeeded
      enabled: true
  bots:
    slack:
      enabled: true
      image:
        repository: tomaszszuster/argocd-notifications
        tag: v0.7.1