argocd-notifications:
  argocdUrl: https://argocd.apps.blah.cloud
  image:
    repository: mylesagray/argocd-notifications
    tag: v1.0.1
  secret:
    create: false
  subscriptions:
    - recipients:
      - slack:kubernetes
  triggers:
    trigger.on-health-degraded: |
      - description: Application has degraded
        send:
        - app-health-degraded
        when: app.status.health.status == 'Degraded'
    trigger.on-sync-failed: |
      - description: Application syncing has failed
        send:
        - app-sync-failed
        when: app.status.operationState.phase in ['Error', 'Failed']
    trigger.on-sync-status-unknown: |
      - description: Application status is 'Unknown'
        send:
        - app-sync-status-unknown
        when: app.status.sync.status == 'Unknown'
    trigger.on-sync-succeeded: |
      - description: Application syncing has succeeded
        send:
        - app-sync-succeeded
        when: app.status.operationState.phase in ['Succeeded']
  bots:
    slack:
      enabled: true
      image:
        repository: mylesagray/argocd-notifications
        tag: v1.0.1