elasticsearch:
  ingress:
    enabled: true
    hosts:
      - host: es.tanzu.blah.cloud
        paths:
        - path: /
  resources:
    requests:
      cpu: null
      memory: null
    limits:
      cpu: null
      memory: null
  extraInitContainers:
   - name: file-permissions
     image: busybox
     command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
     volumeMounts:
     - mountPath: /usr/share/elasticsearch/data
       name: elasticsearch-master
     securityContext:
       privileged: true
       runAsUser: 0