apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-dnsprovider-config
  namespace: ingress
spec:
  encryptedData:
    CF_API_EMAIL: AgAVois5YzQgwuYYU2C/9Setc2yUFTVXLRYTeb/GnrljRXeiYCVF1G6kfqTjoDvCEUZz3Q0WywREO/sGjo1p0zNecr6Dae/Z/xnMcb7jPaan5OmZPREvhLonTcOray9uW6fELXprx5IgyAIthETl4ujzVjQevGDOIuNb8NIdM4ejFiQNZ3XqXKHYCYY6q3XU7nUgM1m3M9J+h6J8q/p5m5rvcG2qKj9DN4+fsDZ9L8VHhKbqg9dvj+BHrut+ueVdEKGQtNj7NdxvHz5Lg6oGen2w/gmz5PrJZMrAZ+atL0yRCAb7WDWLCwtVkfSvOezTyPV0xLfzWvYDy21SQRGCHV4ESkKMlOMHPGufY7X7xxz2mlEGfn37wD9rxF//WYVbxwhNwgjHHQZdeRM3EMinFhCnA3VmA8h/fAK/ZNUsUV6Rc4/k6YBXyciKyJ2AZSYQtVI978nOt/wDejSxiEMjNnV3gIIBJeB9Gv1nAtzQqe0y7+XDYEXs11/m3LlwGqAQDapWePE3ksb0gh4MLSdntyGbtij3j2F0VAZtD1SQRvDZzOPoJghB++/LY4fZJEge7jUy7W0rT1JaSuMkJML25BS6kPSJ40upBIB6y0bBPerZkWbWWS+mhspRRV1UqFU8zQFUf3pfUm5IwzqEsOGyFA7PavgD4frXwPqLpk9yqlsvCktmkOVRdbRNSgsvTQau5GML/esO3mrSDQmYSeG0HPst
    CF_API_KEY: AgBDDvLcFFAyD/mca1nnBNx3yMIUr592R6qIFydseHpd7Z/v8VI2QFKL77uwF4pvgTRK8+R5N77U+E6Aws6WRRXjsM9a93NdzJZO0eleXAhOMcLF3wPsjUGYyPQuql77/P4DklLnuINRAq9GQYJQbJDOLeBCcKiqwcjY4OqVSKrPX9+e5+Z349gRI609SGUMOFeh4xok92S818i7GpJmr6XHryOOdLerg5HWw/yn8r6xOCgfATFd+EsAi7qS3fVBrqzwOqHsac/Q2jgdL6jLwu5cgbEB5063inmAMOZBOGAnpCsu7UBSOBA/8HvOJ7lOt4J7x+UALstagtdGe48DtywY5/BaE9ZFxT0n461qk3N4gGQIq+YDJUmX+1+9m8aY/sHfqDD0m6NqlVkUZXNHHy86zc9jlSuyAlPKupwdKlfVDW5+WpohQqHrMynk+VMNfNbdAOFpKkS/5E3UQflzdYAzXSXL7fCTt0gWVWbJjXhuBPpWLEyEQfZrbg0iJFCVe3wNy7cE7qG6iV5INWwnq5sr0HNWNI3oL7AIfyugcy+gOHFgcRQulqhsBdgpITfM4p3KrdyEylnaYa/9ruUKBzSB2l6y6c6yoh9Pqm388MZ8LtUcWK7wZIee7f8naBf2VFZHw0gnRJMSJgi7z4djNn31o6IC04QPWmk8XkmmWw0o5ksp3sHCXdq/AjsllXEyg95/EpGDUkA2s/sqweIAK5xsHWVx/drp78trFGBYU8xDufwl33JJ
  template:
    metadata:
      creationTimestamp: null
      name: traefik-dnsprovider-config
      namespace: ingress
    type: Opaque

