apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgA+5QOjS4OYPa903ES9rS8PXwZpw30q5ATM5Io2v6w3Sw01vNv2m5IwU7RBtC4E4+o9kN1kBNBXaBXMdBrgAY2oOJKQ0wZKprsUgcHcHcoOccs5fr3G8++lnIOc2FMxHZnR+8KAxew4qIh4XAWhhMFeVTOpjzNrAhSr1QfCQrxsikUHrKZFULY00gmS4nf91bbMY+esLRAqQq65U85PiZZXAe+d08rjl/a7eh1beeC9x1s/LZoWOTDQoG8msKc0WNLvhqosCXgj5vts/LEp3BMFynGEIYh9A00BwFNGdCk5ZwnWf9MiUaEQJq144Q0i+gkwbbSteZFYRG4e84Skj+03cFJg5llctFTuimLVbr/f8Knhk3PnQHgAy7zcyt49tzlWKPIGnb7cwc9GaG+d8VOEBR94Nss5Ni1zIbyKgMkZD3b/T82zNkkuHyrFte5UDOrmpG7/SPqxcdkfC/ZgJlKr11Ee7HBI+UVzkzq1jx9i9j9WMvXnTswjt5BtovhyGugI1DCy5xPlQns4B4BpuyfliNE2WEMpVK69mRam4lYYwOIkfNbrHnM6265LBRT76b2o7A5OT92YRZT3Z24cwWHbiaC5AonzarwlgDpgk+h19PUJtq/BGIhkGgLLB9+IvCUWRm3+bqfXhv6IaCgUrgd424SBswZqOjL8fW/8+9IcK5bfmrR12XKReXc3taJdXV4GtFVfOrhWtpM2a5si2fSG215blKWQ1cNxPixcaaQxKa+nPn9yd0wc
    username: AgBYeMT+6GbVGm+iD/Z8gk4pdHzs7Z9p37nNXf06CYZEKqwtPTgYv0yLk1rt3d4kL0oNIOAxX4vR4eilnVVCyuWU0iBAZY2cTHzWfyGtFt1z1nkgstklpfN1azuycWzu4wQbB75rlzUSRmwwIIoEKbxtMs1ixk9gRkhP5KpjsrjzGc9283H2gQq9HwLCcDmf2mzbO5fFKoFqwirOgow5avp0ln3YdMDWUaT+nc4ZAoEw5KedHO7NlJEwe3jgG9LhebX/N1CXYMfZCzQ8Th1u2X/a2PL+vQMsecr1wBd233GaUF5HlC+XR9Q3XZBVRAF4SUSvPHkARt2a7hLd3J3vHp4lqhFAHF1FQ+ldzz1QEFENM9XA3k/oLGKQr22b36eFHErVpl28sfgSk5dr8NRp3HiqwdW4r5f9jCeSBAtKQKDvZzgbhpznC9GBneNzYNDhiA3wwK2fIn0Nv5I43/sAfOGAhl6SXEUBmHU51MtysdA2TtEZwKvEv6MyFpM5lLMniLf4tyoflu2HKXojwH0ptKMxwLiz0y3XFYiOM2NZHl9Jy3OLekNBcEnba22wjT5OIbOuchdEWAXTMiS6SjjQihn7Js2nZ8unKDa8H6SKew+8xkwTb8L3YRl135wEAsSoA9wmQ1pAbz3S4Ap0RsJAquZiIqqFa4JLzTrdfPgw4u9yO4lmmo7bZwyusQ8YArIXpR6Agl3ApOjC9zZv
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

