kibana:
  ingress:
    enabled: true
    hosts:
      - host: kibana.tanzu.blah.cloud
        paths:
        - path: /
  resources:
    requests:
      cpu: null
    limits:
      cpu: null
  elasticsearchHosts: "https://es.tanzu.blah.cloud"